### ISSUE TITLE
Support the ability to Label Sources using GitVersion.NuGetVersion

### ISSUE THREAD

**Issue by JoeBrockhaus** [GitTools/GitVersion#1115]
This piggybacks off another issue elsewhere.. 

https://github.com/Microsoft/vsts-agent/issues/716
Not sure if this is something that should/could be solved here or there. 

Basically, because the Finalize Build steps are not run on the agent, we're unable to add a tag using the NuGetVersion.

**Comment by pascalberger** [comment]
I don't think there is anything we can do inside of the GitVersion task about this as long as VSTS doesn't provide an appropriate API. GitVersion currently just defines the variables using the [`##vso[task.setvariable]value` command](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md). Variables are explicitely defined in the task context, and therefor available for subsequent tasks, but not outside of the context.

A special case is the build number for which a special command exists [`##vso[build.updatebuildnumber]build number`](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md) which we are using.

A workaround can be to add an additional task which adds the tag, which will work since the task will be in the same context and have therefore access to the variable.

**Comment by JakeGinnivan** [comment]
Looks like we can't do anything here, going to close this issue :)

**Comment by JakeGinnivan** [comment]
Also, the actual labeling I think is tied to the release process, not the version generation process. I would argue this functionality should never end up in GitVersion.

That said, I have asked for the same thing!
