### ISSUE TITLE
GitVersion Task in Team Services throws exception if mode is set to Mainline

### ISSUE THREAD

**Issue by Franklin89** [GitTools/GitVersion#1123]
I just created my build on VSO and used the GitVersion task from the marketplace. We are using the _Mainline_ mode. The Task execution fails with the following exception:

`2016-12-21T07:30:32.1711902Z YamlDotNet.Core.YamlException: (Line: 1, Col: 7, Idx: 6) - (Line: 1, Col: 15, Idx: 14): Exception during deserialization ---> System.ArgumentException: Requested value 'Mainline' was not found.`

This works fine on my local machine and my laptop.
It is using the version:

`2016-12-21T07:30:24.1051319Z ==============================================================================
2016-12-21T07:30:24.1051319Z Task         : GitVersion Task
2016-12-21T07:30:24.1051319Z Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
2016-12-21T07:30:24.1051319Z Version      : 3.6.5
2016-12-21T07:30:24.1051319Z Author       : GitVersion Contributors
2016-12-21T07:30:24.1051319Z Help         : See the [documentation](http://gitversion.readthedocs.org/en/latest/) for help
2016-12-21T07:30:24.1051319Z ==============================================================================`

**Comment by pascalberger** [comment]
The GitVersion task in the marketplace is the latest released version 3.x. Mainline mode was introduced in 4.x which currently still is in beta and not available from the VSTS marketplace.

If you currently want to use mainline mode together with VSTS you have several possibilities:
* Install latest beta package GitVersion through Chocolatey during build and call it from a command line task (or if you have on-prem build agents you can also install them fix)
* Use the GitVersion NuGet package if that is an option for you

**Comment by Franklin89** [comment]
Thanks for the fast comment.

**Comment by stoopered** [comment]
I am trying to use the Nuget version, but when trying to use Mainline, it never increases the patch version. I have one label specifying the Major.Minor.Patch as 1.1.0, the first merge increments it to 1.1.1, but after that it stops. 

Here is my exported yml

Major: 1
Minor: 1
Patch: 1
PreReleaseTag: 
PreReleaseTagWithDash: 
PreReleaseLabel: 
PreReleaseNumber: 
BuildMetaData: 4
BuildMetaDataPadded: 0004
FullBuildMetaData: 4.Branch.master.Sha.5f11306b4bafeb3744afa2d2e4e78e556ba4e157
MajorMinorPatch: 1.1.1
SemVer: 1.1.1
LegacySemVer: 1.1.1
LegacySemVerPadded: 1.1.1
AssemblySemVer: 1.1.1.0
AssemblySemFileVer: 1.1.1.0
FullSemVer: 1.1.1+4
InformationalVersion: 1.1.1+4.Branch.master.Sha.5f11306b4bafeb3744afa2d2e4e78e556ba4e157
BranchName: master
Sha: 5f11306b4bafeb3744afa2d2e4e78e556ba4e157
NuGetVersionV2: 1.1.1
NuGetVersion: 1.1.1
NuGetPreReleaseTagV2: 
NuGetPreReleaseTag: 
CommitsSinceVersionSource: 4
CommitsSinceVersionSourcePadded: 0004
CommitDate: 2018-05-22



And here is my yaml config

assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
branches:
  master:
    mode: Mainline
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: master
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true


I am expecting it to increase from 1.1.1 to 1.1.2 when I do a pull request from a feature branch.

**Comment by alpeshv** [comment]
Try [this solution](https://github.com/GitTools/GitVersion/issues/1160#issuecomment-381517122)
