### ISSUE TITLE
GitVersionTask 3.6.5 ignoring GitVersion.yml in project dir

### ISSUE THREAD

**Issue by asherber** [GitTools/GitVersion#1170]
Given a VS solution with one or more projects that have the `GitVersionTask` NuGet package installed, GitVersion will look only in the solution dir for `GitVersion.yml` and will ignore any `GitVersion.yml` in the applicable project dir. 

The docs at http://gitversion.readthedocs.io/en/latest/configuration/ say that I should be able to put the config file in any solution subdirectory, "in case you have a single repository for more than one project" and want to set different GitVersion parameters on each.

GitVersion CLI run from the project directory behaves correctly.

**Comment by asherber** [comment]
See #1124 for more discussion, and especially https://github.com/GitTools/GitVersion/issues/1124#issuecomment-269882437

**Comment by gparlakov** [comment]
Hi all, I want to share a workaround that seems to be working:
1. GitVersion uses $(Build.SourcesDirectory) to see where the sources are located - [src](https://github.com/GitTools/GitVersion/search?q=SourcesDirectory&unscoped_q=SourcesDirectory)
2. We can change this using [logging commands](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md#logging-commands)
3. Workaround is to set the Build.SourcesDirectory before GitVersion task 
4. Then gitVersion uses the GitVersion.yml from the project folder (Build.SourceDirectory) and voila - works

After that you might want to roll back the change or not - depending on your need. For me it seems it is nice to scope down to the only nuget package from the collection of nuget packages in our nugetPackages monorepo.

**Comment by isengrim613** [comment]
Forgive me for being confused but how does this help in versioning per project in a single git repo?

```
-- root (where the .git is)
 +- project1
   +- gitversion.yml
 +- project2
   +- gitversion.yml
 +- gitversion.yml
```

If the git version ymls in the project subfolders are honored, can i have a different version for project1 and project2?

Like,

* project 1 is at version 1.1.20-commit50
* project 2 is at version 2.0.0-commit100

I believe the major and minor versions are based on tagging, the patch number could be by tag or commit number and the build number is based on commits since the last tag.

How do I set this up? Do I need to have a specific format for tags to say that that tag is meant for project1? 

Is it possible to setup commit count tracking by folder too?

**Comment by cytron201** [comment]
Any further comments on this scenario? I can see how @gparlakov workaround would handle the M.M.P versions as you could control these in the gitversion config scoped per solution, but @isen-ng point is that the pre-prelease tags will still need some way to be generated per solution.

I can't see any other way of achieving this for a mono-repo setup.

**Comment by bdubaut** [comment]
This is exactly what I am trying to do right now, how can I help move this forward?

**Comment by freePerep** [comment]
This is also for me exactly what I need for my project.

**Comment by garfbradaz** [comment]
Any news on this?

**Comment by rose-a** [comment]
This also applies to `GitVersion.yml` in the git root directory, when the solution file resides in a subdirectory...

**Comment by asbjornu** [comment]
Is this still a problem in GitVersion 5?

**Comment by Ranjandas** [comment]
Is there any documentation on how to do this? A quick and dirty try gave me this error.

```
➜  src git:(master) ✗ gitversion
INFO [02/01/20 0:19:30:35] Working directory: /Users/ranjan/workspace/github/gitversion-test/srcINFO [02/01/20 0:19:30:37] IsDynamicGitRepository: FalseINFO [02/01/20 0:19:30:38] Returning Project Root from DotGitDirectory: /Users/ranjan/workspace/github/gitversion-test/.git/ - /Users/ranjan/workspace/github/gitversion-test/WARN [02/01/20 0:19:30:38] An error occurred:
Ambiguous config file selection from '/Users/ranjan/workspace/github/gitversion-test/src/GitVersion.yml' and '/Users/ranjan/workspace/github/gitversion-test/GitVersion.yml'%
```

**Comment by brunobertechini** [comment]
Any update on versioning per monorepo subfolder?

**Comment by marcusl** [comment]
Versioning differently in different subfolders based on different tag-prefixes worked well for me in 5.

@brunobertechini Do you have some specific problem?

**Comment by brunobertechini** [comment]
@marcusl can you please point me to any documentation about it? I couldn't make it work.

**Comment by marcusl** [comment]
Set tag-prefix different in yaml and run gitversion in each folder is what I've done.

https://gitversion.net/docs/configuration <- tag-prefix is documented there.

**Comment by leonids2005** [comment]
@marcusl  sorry for ignorance but could you please elaborate a bit more on how I can use tag-prefix so gitversion will "calculate"  different versions for different projects in monorepo?

thank you.

**Comment by marcusl** [comment]
> @marcusl sorry for ignorance but could you please elaborate a bit more on how I can use tag-prefix so gitversion will "calculate" different versions for different projects in monorepo?
> 
> thank you.

Hi Leonid!

It's quite trivial actually.

1. create different gitverison.yml files in subfolders, like foo/gitverison.yml and bar/gitversion.yml
2. setup different tag prefixes (f.ex. foo/v  and bar/v )
3. tag repo with foo/v1.2 and bar/v3.1 at right places
4. run gitversion in either folder (or pointing to the right gitversion.yml) and it will figure out different version numbers for different subfolders/subprojects.

Hope it helps. :)

**Comment by Jaykul** [comment]
The problem with using tag-prefix for monorepo versioning is that you'll still be incrementing **by** too much, because GitVersion is still going to _count all the commits_ (not just the ones which touch each subfolder) when it calculates new version numbers. It's even worse if you use commit messages to bump the version. 

If you try to use multiple GitVersion.yml files with separate folders, you have to use **only** `next-version` in gitversion.yml to increment the version, **or** you have to change the `+semver:` pattern for each GitVersion.yml

**Comment by asbjornu** [comment]
@Jaykul, it's not a given that commit counting should increment the version number, @Jaykul. This depends on the `mode` GitVersion is running under. When this issue was created, `mode: Mainline` and commit message increment wasn't even implemented and I believe the same to be the case for #1268 (which is why it was marked a duplicate of this issue).

Are you not able to use a `mode` and process of development that does not cause GitVersion to inadvertently increment the version number of the sub-projects in your monorepo?
