### ISSUE TITLE
CI build not using custom configuration

### ISSUE THREAD

**Issue by stephen-roberts** [GitTools/GitVersion#1207]
Hi,

I am just getting started with gitversion and have made a small change to the configuration which has created a gitversion.yml file in the root of my repository. If I run gitversion from the command line locally I get the correct output, but when it reaches CI gitversion is not producing the correct version number. It appears it is ignoring the gitversion.yml file even though it is checked in and is definitely present on the build agent. For reference I am using TeamCity and the build step runs the following command:
C:\ProgramData\Chocolatey\bin\gitversion.exe /updateAssemblyInfo /output buildserver /nofetch

Please could someone advise why my configuration is not being picked up during the CI build?

Thanks,
Stephen

**Comment by pavlovps** [comment]
@stephen-roberts I haven't tried using GitVersion via Chocolately but tried using GitVersion CLI located in subfolder of checkout directory, that worked nicely (just keep GitVersion.yml in the root of repo). Probably the reason is working directory is not set correctly or not set at all. Why don't you want include GitVersion as msbuild task? That would make equal build from VS and via msbuild

**Comment by stephen-roberts** [comment]
Thanks for your reply. We are using the TeamCity build runner so that we can get the version numbers out of GitVersion and use them in the build for creating packages. Not sure if this is possible with the MSBuild task? I am also trying to avoid too much change to our TeamCity builds as we have a base project that is inherited across all our solutions, but I will try GitVersion CLI in a subfolder as we could then change the build config on a per project basis. Thanks again.

**Comment by pavlovps** [comment]
@stephen-roberts we're using TeamCity as well. It perfectly suits with GitVersion as msbuild task: GitVersion updates build number in TeamCity out-of-the-box - nothing to be specifically done. The only thing you have to do is defining environment variable [Git_Branch](https://gitversion.readthedocs.io/en/latest/build-server-support/build-server/teamcity/) targeting your VCS root (instead of {vcsid} mentioned in the help you have to put your real VCS root - TeamCity will guide you with IntelliSense. BTW same for GitVersion CLI - it also requires Git_Branch environment variable in TeamCity

**Comment by stephen-roberts** [comment]
@pavlovps thanks, I'll take a look
