### ISSUE TITLE
Wrong versions in NuGet dependencies when using .NET Core MSBuild

### ISSUE THREAD

**Issue by prochnowc** [GitTools/GitVersion#1209]
Using GitVersionTask (tried latest 3.x and 4.x) `msbuild /t:pack` does not generate correctly versioned dependencies for cross-project referenced packages. All dependencies in nuspec have version "1.0" (default value).

**Comment by bording** [comment]
I've just hit this as well while upgrading some projects to the new SDK-style csproj format. These projects are targeting .NET Framework, not .NET Core, so this problem is related to how project references work in the new project format, and not the target framework.

Each individual assembly is versioned correctly, but it seems that the appropriate version information is not made available to the project reference, so when that project reference is turned into a dependency in the nuspec, it is still 1.0.0.

I'm actually not sure if this is something fixable by GitVersion or not, because if you take a look at the `project.assets.json`  restore file for the project that contains the reference, you'll see that the 1.0.0 version is there as well. Does this mean that the version information has to exist already before restore occurs?

**Comment by dazinator** [comment]
I just hit this issue too.. I'm preying I don't have to go down the path of creating nuspec's manually.

**Comment by dazinator** [comment]
Have opened: https://github.com/dotnet/sdk/issues/1320

**Comment by dazinator** [comment]
The following workaround seems to work. When you do a restore, specify the version at that point too.

For example:

`dotnet msbuild "/t:Restore" /p:Version="1.0.0-alpha0001" /p:Configuration=Release`

Now when you `pack` it looks better.

**Comment by bording** [comment]
@dazinator That would only work if you already know what the version is going to be, but the whole point of GitVersion is that it calculates the version, so you don't know in advance what value you should use to restore with.

**Comment by bording** [comment]
I suppose as a last resort workaround that works, but that's a lot of additional steps to have to coordinate/script as part of a build process. It also means I'd likely need to integrate the commandline version of GitVersion where right now I'm only using GitVersionTask.

**Comment by dazinator** [comment]
Yeah it's a pain isn't it. That's why I consider this suggestion a workaround - hope it helped you out in the meantime.

**Comment by prochnowc** [comment]
This was fixed in the .NET Core SDK.
