### ISSUE TITLE
GitVersion.BranchConfig Serialization/Deserialization Issue

### ISSUE THREAD

**Issue by d-dantte** [GitTools/GitVersion#1210]
I installed the GitVersionTask nuget package on my visual studio project.
Now when i build, i get  the following in my Output window

`System.Runtime.Serialization.SerializationException: Property 'regex' not found on type 'GitVersion.BranchConfig'`

Done lots of searching online and cant find any similar errors/solutions, and being a newbie, i'm not entirely sure what next to do.

Thanks in advance :)

**Comment by Kevin-Deason** [comment]
Their documentation is not in line with the GitVersion Release. I am encountering numerous issues because of this.

Remove the regex setting and it works. But if you use the default configuration from their documents you will get more errors.

I am now stuck with the below error:
Multiple branch configurations match the current branch branchName of 'release/Testing_GitVersion'. Matching configurations: 'release, releases?[/-]' and can't seem to find how to fix this

My config is:
assembly-versioning-scheme: None
assembly-informational-format: '{FullSemVer}'
ignore:
  sha: []
  commits-before: 2017-04-10T16:08:00
branches:
  master:
    mode: ContinuousDelivery
    tag: ''
  release:
    mode: ContinuousDelivery
    tag: rc
  feature:
    mode: ContinuousDelivery
    tag: alpha.{BranchName}
  hotfix:
    mode: ContinuousDelivery
    tag: rc
  develop:
    mode: ContinuousDeployment
    tag: beta

**Comment by JakeGinnivan** [comment]
v4 introduced the regex field. v3 doesn't have this.

What version are you two using?

**Comment by Kevin-Deason** [comment]
I ended up cloning the source, making some changes to suit my needs and packaged it for using in vnext build task. It seems the vnext build task that is on the public VS marketplace is the old v3 version which is why it's not working.

**Comment by d-dantte** [comment]
@JakeGinnivan i'm on version 3 apparently. Also, the GitVersion build task on TFS seems to be version 3, not 4, which explains why its failing - just as @Kevin-Deason said.
What options are available in version 3 (while we wait for TFS to get version 4 :D), that can allow me configure the branches?

**Comment by asbjornu** [comment]
The reason v4 isn't on the VS Marketplace is because it didn't support pre-release versions, wasn't it?

**Comment by sdunnin** [comment]
Is there a way to determine what the version of GitVersion running is via the command line?

**Comment by asbjornu** [comment]
@sdunnin: The `/version` switch was added in #1155. Have you tried that?

**Comment by sdunnin** [comment]
No I have not. Will check it out. Thanks!

**Comment by nyn3x** [comment]
I encounter the same problem - is there going to be the v4 release on the marketplace any time?

**Comment by martinfletcher** [comment]
Please release a v4 version to the marketplace
