### ISSUE TITLE
Duplicate Assembly attribute error when using constants

### ISSUE THREAD

**Issue by Freakazoid182** [GitTools/GitVersion#1212]
Related to #871 and #760

Using a shared assembly info I am setting my version number in a constant string 
```
[assembly: AssemblyVersion(AssemblyInfo.Version)]
[assembly: AssemblyFileVersion(AssemblyInfo.FileVersion)]
[assembly: AssemblyInformationalVersion(AssemblyInfo.InformationalVersion)]
```
Looking at the RegEx to replace the attributes, this is not going to work as it requires quotation marks in the between the parentheses of the attribute.

This of course results in duplicate Assembly attributes, as it will try to append new attributes, assuming there are none.

I don't understand why the RegEx in [AssemblyInfoFileUpdate.cs](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionExe/AssemblyInfoFileUpdate.cs#L28) requires the quotation marks
RegEx:
`AssemblyVersion(Attribute)?\s*\(\s*"[^""]*"\s*\)`

Would it not be better to just replace any content (including whitespace) between the parentheses of the Attribute?
RegEx:
`AssemblyVersion(Attribute)?\s*\(\s*\S*\s*\)`

Of course, the string that's replacing the original should then have the quotation marks again. 
Probably this would require some refactoring on AssemblyInfoFileUpdate.cs and maybe some other places. I'm glad to make a PR, does anyone see any issues with this?

**Comment by asbjornu** [comment]
I agree that the quotes shouldn't be necessary. Referencing a constant should also work. The only itch I have with this is #883, since it would have to be fixed twice. I would therefore much rather see that the `AssemblyInfo` patching code be moved into `GitVersionCore` and then fixed there once and for all. You just go ahead and submit the pull request you feel like, but I just wanted you to be aware of the challenges ahead and possible paths you might take.

**Comment by Freakazoid182** [comment]
Thanks, good to know the future plans for this. I'll try to keep this in mind.
