### ISSUE TITLE
Is there a way to omit default branch specifications?

### ISSUE THREAD

**Issue by tomasaschan** [GitTools/GitVersion#1301]
I want to use a very simple versioning scheme, where any commit that has a tag `vX.Y.Z` is versioned with that tag number, any commit without such a tag is versioned with the prerelease tag `beta` on master and `alpha` on any other branch.

I've tried the following branch specification, but since it's merged with the built-in branch specs, I get multiple matching schemes for a pull request head (e.g. `pull/14`).

```yml
mode: ContinuousDelivery
next-version: 0.1.0
branches:
  master:
    tag: beta
  (?!master):
    tag: alpha
ignore:
  sha: []
```

Is there a way to configure GitVersion to do what I want?

**Comment by asbjornu** [comment]
Wanting different versioning strategies on the same branch sounds very wonky and is not something GitVersion currently supports afaik. Why can't you keep `master` for stable builds and have a `develop` branch or `feature/*` branches for unstable builds?

**Comment by tlycken** [comment]
I don't want different versioning schemes for the same branch. I want a simpler set of schemes than the defaults seem to allow :)

Basically, "unless there's a git tag here, label everything on master as `beta`, everything else as `alpha`". The defaults don't let me, because there are then multiple matches for e.g. `pull/*`.

My solution was to include all of them in the same regex, but I would rather not have to. Here's my current config: https://github.com/tlycken/RdbmsEventStore/blob/master/GitVersion.yml It's evolved since, but the principle stands - in the third rule I have to iterate a bunch of stuff I don't care about to avoid clashing with default rules.

**Comment by asbjornu** [comment]
@tlycken, I understand how that might seem like a simpler scheme, but from GitVersion's perspective, it's more complex, because given the same branch `master`, you want two different versioning schemes depending on the existence of a tag or not.

I'm glad you figured out a solution, although I agree it's not a good one. In version 4 of GitVersion, you might get a cleaner config file at least, since the regex is moved into a [`regex` key](http://gitversion.readthedocs.io/en/latest/configuration/#regex).

**Comment by tlycken** [comment]
@asbjornu But that applies anyway - a tag _anywhere_ gives me that tag (or the highest-version tag if there are several) regardless of which branch I'm on, no?

**Comment by asbjornu** [comment]
True, true. Not sure what I was on about. Is it possible set `tag: alpha` at the root level and then `tag: beta` for `master` only?

**Comment by tlycken** [comment]
You mean like this?

```
branches:
  tag: alpha
  master:
     tag: beta
```

I'll try and get back to you with results :)

**Comment by asbjornu** [comment]
I was thinking more like this:

```yml
tag: alpha
branches:
  master:
    tag: beta
```

**Comment by davidarcher** [comment]
I also ran into a similar problem when trying to use Mainline mode for per-commit version incrementing/counting. My team doesn't use GitFlow but it seems there is no built-in way to fully override the default GitFlow branch configs. I've looked through some of the GitVersion code and I found a number of places where the code is "falling back" to hardcoded GitFlow conventions which I suspect is making it harder for a lot of people to actually be able to use it if they don't follow GitFlow completely.
