### ISSUE TITLE
Is it possible to have the result of git rev-list --count in a variable?

### ISSUE THREAD

**Issue by chrbkr** [GitTools/GitVersion#1345]
In our project, we switched from SVN to git. The versioning scheme was `<major>.<minor>.<patch>.<revision>`.

For continuity, I wanted to keep this scheme, by getting the equivalent of the SVN revision via `git rev-list --count HEAD`.

Is there a variable in GitVersion I can use for this? Or can this command be invoked in some other way when using GitVersionTask?

**Comment by JakeGinnivan** [comment]
This particular variable is not, we have a similar variable which is BuildMetaData, but this counts the commits since the version changed.

**Comment by chrbkr** [comment]
I see, thank you. Is there a way to call an external command in GitVersionTask or is the only possibility using GitVersion in a BeforeBuild task?

**Comment by jbaehr** [comment]
Please note that putting something like a svn revision or `git rev-list --count HEAD` in a version is not save in the long run. On Windows each of the four parts of a version can only hold 16 bits; see https://blogs.msdn.microsoft.com/msbuild/2007/01/03/why-are-build-numbers-limited-to-65535/
So after 65535 commits you get into trouble. And people already got into such trouble, just search on stack-overflow...

As I was looking for a solution for strictly monotonic increasing version numbers (to satisfy Windows Installer's requirements for "Major Upgrades") in the `AssemblyFileVersionAttribute` I was also tempted to simply use the total number of commits as the fourth digit. And because our repo had already more then 140k commits at that time I did some research. Indeed, it was a good idea to go another route...
(Our current approach is to use the build number from the CI-server; that can easily be reset when opening a release branch)

**Comment by asbjornu** [comment]
I think #1385 might provide a solution to this by allowing the result of `git rev-list --count HEAD` to be exposed as an environment variable and then that variable being used by GitVersion. Would that help, @chrbkr?

**Comment by chrbkr** [comment]
Sorry for the late response. Yes, this would definitely help.  Would that be hardcoded or would it be possible to set some options? In order to mitigate the 16 bit limitation pointed out by @jbaehr it might be useful to use `git rev-list HEAD --count --first-parent` (on master) instead, so only releases are counted (assuming a git-flow approach).

**Comment by jbaehr** [comment]
@chrbkr just be careful with GitVersion's cache. We run GitVersion.exe with the `/nocache`-flag prior to the build, setup a "weighted prerelease number" env-var by applying a prerelease-label based offset to the commits-since-version-source and use that for the fourth digit (#1433 is an attempt to automate this further). The first call of the GitVersionTask creates the cache with the env-var already in place. This cache is then used by all subsequent GitVerionTask invocations.  
(just using build number from the CI-server does not play well with Jenkins' multi-branch  
pipelines; thus we don't use what I described in an earlier comment anymore)

When you just set the env-var and only relies on GitVersionTask, you may have to find a way to tell the Task to ignore the cache (which will have a performance impact on large repos when building many projects). Or ensure the env-var is there in all cases.

Finally just use your env-var in GitVersion's format strings, see the "*-format" keys in https://gitversion.readthedocs.io/en/stable/configuration/

**Comment by asbjornu** [comment]
Can't you use the build counter as a parameter in the version number then, @vincentcastagna?

**Comment by vincentcastagna** [comment]
Hey @asbjornu can you elaborate please ? Where to get that build counter (you mean the git count ) ?

**Comment by asbjornu** [comment]
You get that from the build system. TeamCity exposes a variable called `build.counter`, for instance.

**Comment by vincentcastagna** [comment]
@asbjornu any official doc about this variable ? Cause can't find.

**Comment by asbjornu** [comment]
You will have to check with your build server. Which one do you use, @vincentcastagna?
