### ISSUE TITLE
Add version bumping strategy 'commit message'

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#137]
I would like to bump the major or minor by having certain keywords in my commit message..

It would be done via two configuration properties, both accepting a RegEx value with the keys and their default values being:

``` yaml
major-version-bump-message: (\+semver:.?breaking|breaking:)
minor-version-bump-message: (\+semver:.?(feature|minor)|(feature|minor):)
```

The match should be case insensitive. 

This will match `Api change doing blah +semver: breaking` and `breaking: Api change doing blah`  
And minor can be `new feature description +semver: feature` or `feature: new feature description`

**Comment by andreasohlund** [comment]
I like the `+gv: breaking` , pretty similar to: https://github.com/boennemann/semantic-release#how-does-this-work

That said since we're actually talking about a semver breaking change should we consider: `semver: breaking change` to be less gitversion specific?

**Comment by pvandervelde** [comment]
+1 for the +semver:breaking option. Maybe the other option should then also be +semver:feature?

**Comment by JakeGinnivan** [comment]
Why not make this configurable.

major-version-bump-message: <regex>

:)

**Comment by andreasohlund** [comment]
Yea, `+semver: feature` sounds good.

>Why not make this configurable.

at least as the default option :)

**Comment by JakeGinnivan** [comment]
So what about

``` yaml
major-version-bump-message: \+semver: breaking
minor-version-bump-message: \+semver:(feature|minor)
```

**Comment by andreasohlund** [comment]
+1

**Comment by JakeGinnivan** [comment]
Updated issue description. It is up for grabs so anyone can grab it :)

**Comment by robdmoore** [comment]
Great idea!

**Comment by roryprimrose** [comment]
Are there any special rules around using this? I've tried an empty commit against develop (local), a commit with a change to the readme.md in a feature branch (also local) and I still see the existing versioning scheme. I've tried with commit messages of

+semver: minor

and then tried

Version bump to 2.4
+semver: minor

Still no joy. Are there special conditions that cause this comment to be actioned?

**Comment by roryprimrose** [comment]
Hmmm, I think this is my lack of understanding. I'm trying to bump minor on a develop branch after I have created a release-2.3 branch which is going through a release candidate phase. 

The last known version source on the develop branch was a v2.2.9 tag. The develop builds were correctly building 2.3.0 builds based on the 2.2.9 tag. I had assumed that adding a commit message to bump minor would have taken 2.3.0 to 2.4.0. I guess it doesn't because it is bumping from the 2.2.9 tag and coming up with the 2.3.0 version again.

I can't tag 2.3.0 anywhere because it hasn't been finalised in the release-2.3 branch. I am assuming that my only option is to put a next-version: 2.4.0 into the GitVersion.yml in the develop branch to get the desired result.
