### ISSUE TITLE
Use 'const string' in GitVersionInformation.cs

### ISSUE THREAD

**Issue by mgnslndh** [GitTools/GitVersion#1376]
How about using a `const string` instead of a `static string` in the generated `GitVersionInformation.cs`? This would make it possible to use the values in attributes such as 

```
[assembly: AssemblyConfiguration(GitVersionInformation.PreReleaseLabel)]
```

https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/GitVersionInformationResources/AddFormats/GitVersionInformation.cs

**Comment by jbaehr** [comment]
I support this idea.

(The only point in favor of `static readonly string` would be that `const string` gets inlined at compile-time. But since the whole class is private you cannot reference this information from a foreign assembly anyway...)

It's a breaking change for those using reflection, though. Anyway, prior to a final release this is acceptable and I assume only a few people to be affected. And the benefits outweigh the drawbacks by far.
