### ISSUE TITLE
GitVersion produces different BuildMetaData once commit is tagged

### ISSUE THREAD

**Issue by sebastianlux** [GitTools/GitVersion#1397]
**Repro Steps**
*First commit*
*Second commit* <- Tagged with 1.2.0
*Third commit* <- pump minor via commit msg
*Fourth commit* 

->Fourth commit now produces version number *1.3.0+2*
-> Now tag the *fourth commit* with v1.3.0, aka we have released *1.3.0+2*

**Expected**
When building the *fourth commit*, the exact same version information are produced by *GitVersion*, meaning *1.3.0+2*

**Actual**
The *fourth commit* produces version information without any *BuildMetaData*, meaning the +2 is missing. 

We usually take a build, test it, release it, and then tag the commit as released. 
We do not know before the actual test whether we want to release (aka tag) the commit or not. But with this approach we are forced to tag the commit before the actual test to ensure that the version number of the commit does not change.

Edit:
Tested with GitVersion 3.6.5 and 4.0.0-beta0012

**Comment by sebastianlux** [comment]
Any update on this?

**Comment by jklaus** [comment]
I am seeing strange behavior with the metadata being off now as well.  Started a couple weeks back.

**Comment by asbjornu** [comment]
With which version of GitVersion are you experiencing this, @jklaus?

**Comment by jklaus** [comment]
@asbjornu 5.0.1, in Azure DevOps.

**Comment by asbjornu** [comment]
Could you please update to version 5.3.4 and see whether the problem is reproducable there as well?

**Comment by jklaus** [comment]
I can investigate it but I think we're just using w/e the latest version is that the default build step installs.  Not sure if it will allow me to download that far forward from where it currently is.

**Comment by jklaus** [comment]
@asbjornu scratch that.. looks like the step they're using has been deprecated.  I'll tell them to install and port to the latest step, that's likely what the issue is.

**Comment by asbjornu** [comment]
I just realised that the "bug" experienced here is **by design**. A tag will reset the commit count. That's how GitVersion works.

**Comment by jklaus** [comment]
It used to behave such that it was commits ahead of mainline though.. not commits ahead of the current branch.

**Comment by jklaus** [comment]
@asbjornu - that said we've been on 5.0.1 for a very long time w/o issues until recently so I assume the issue is more rooted in either the version of .Net Core 2.1 that our agents are installing or something else ADO/agent specific.  That said, I'm going to have them port from GitTools.GitVersion to GitTools.UseGitVersion which should bring in the latest GitVersion version and will reassess.  Its worth noting that they're currently creating release branches for things in the RC phase so we have a bit of a customized GitVersion.yml around that.  Using branch naming as a methodology to determine major, minor, or patch incrementation.  That said, all of this worked fine with GV version 5.0.1 up until probably a month or two ago now.  The only thing that has varied in that timespan is whatever changes MS has made to the ADO hosted agents.  They're constantly rolling out patches to .Net Core 2.X/3.X so I suspect the version of that we're getting now isn't playing well with an old version of GV.

**Comment by asbjornu** [comment]
@arturcic, is `UseGitVersion` the recommended way to use GitVersion in AzDO these days?

**Comment by arturcic** [comment]
Well I would recommend to give a try the GitTools version, and fill in issues, as that's the way to go. As for the UseGitversion, we don't have resources to fix it

**Comment by jklaus** [comment]
@arturcic - are there known issues with UseGitVersion?  I've tried leveraging it on a .Net Core 3.1 build and its having issues installing.  The agents are currently pulling 3.1.300.

**Comment by HHobeck** [comment]
Gitversion Version:
5.3.4+Branch.master.Sha.be48ce3ac7f048c869fe80b8c8e648ebf4a7e360

User Story:
I'm using gitversion and use the GitFlow workflow as a merging branching strategy. This works quite well as soon the version labeling and the release merging in master comes in place. My build and release workflow is like the reporter of this issue. That means I create a release candidate (RC) e.g. 2.4.0.3 in a releases branch and going to test it somehow in the test environment. After this version has been proofed I define it as release to manufacturing (RTM) and deploy the exact same artefacts on the production environment and create a nuget package 2.4.0,0 containing the 2.4.0.3 DLLs. Note no new artefact has been compiled on master or somewhere else. Now I merge the version from releases branch to master, create a label (with three or four numbers depending if I merge with --no-ff) and delete the releases branch. At this point the source code in master is the same like I had in the releases branch before. I know it is possible that the version differs because of hotfixes in master but I ensure this in my process using git cherry -v origin/releases/2.4.0 origin/master command before merging. If I take the labeled source code from master I get the version 2.4.0.0 instead of 2.4.0.3.

P.s.:
@asbjornu: I'm not sure if it is a bug or a unsupported feature. But just to say it is by design is for me not understandable.  I can tell you that in my opinion gitversion has been developed to support the process of creating product version including semantic versioning. In my case I'm still convenient with the semantic version process because the semantic version number comes in place at this moment I create a nuget package. We should think about it to introduce a new field or something like that to support the semantic version with three numbers as well as the release version with four numbers greater zero.

P.p.s.:
At this moment the version of gitversion is quite buggy. Sometimes it creates no leading zero after labeling and sometimes it does. If is is per design why it behaves not consistently?

**Comment by asbjornu** [comment]
Please use the [GitTolls Task](https://marketplace.visualstudio.com/items?itemName=gittools.gittools) instead of `UseGitVersion`. The latter is not maintained.

**Comment by asbjornu** [comment]
@HHobeck, just to be clear, when you write "label" do you mean `git tag`?

**Comment by HHobeck** [comment]
@asbjornu: Yes that is what I mean. If I label the released source code in master I use the command `git tag 2.0.4.3` for instance. It might be also an idea to use just `git tag 2.0.4` and let gitversion find out the last number.

**Comment by asbjornu** [comment]
@HHobeck, I don't think GitVersion plays well with four-part version numbers. GitVersion supports [SemVer 2.0](https://semver.org/) which only has `major.minor.patch` and an optional pre-relase label separated with `-`.

If you want to support four-part version numbers you can do that by customizing the format, but that is only used for how GitVersion serializes version numbers and does not affect its internal modus operandi, such as calculation.

**Comment by HHobeck** [comment]
@asbjornu: Yes I understand that for the current version of GitVersion. If you ask me GitVersion should support a revision number in future releases. I mean semi versioning comes in place at this point you create a final package for the end user. That's good. But that is the point the process of creating software is much more complex and not just about creating a final package. The semi version number is just a small part of it. The scenario I have described is quite common and it's a shame that GitVersion is not supporting it.

**Comment by asbjornu** [comment]
I wouldn't oppose GitVersion supporting this, but I don't think you can wait for anyone else to implement this for you. If you want to spend time implemeting this, adding required tests, etc., I would be happy to merge it, provided it doesn't break any of our existing supported use cases.

**Comment by arturcic** [comment]
> @asbjornu: Yes I understand that for the current version of GitVersion. If you ask me GitVersion should support a revision number in future releases. I mean semi versioning comes in place at this point you create a final package for the end user. That's good. But that is the point the process of creating software is much more complex and not just about creating a final package. The semi version number is just a small part of it. The scenario I have described is quite common and it's a shame that GitVersion is not supporting it.

@HHobeck I would prefer not to see "shame" in anyones comments, especially if it's related to the decisions made by maintainers of a project. As the repository's description says - `Easy Semantic Versioning (http://semver.org) for projects using Git` - we support Semantic version, that was the intention of the project. It's not a tool that can handle any versioning schemas usable today in software development.
