### ISSUE TITLE
Gitversion is stuck in cmd

### ISSUE THREAD

**Issue by diman82** [GitTools/GitVersion#1418]
Running 'gitversion' from command line makes it stuck/run forever (2 processes in windows task manager, need to either kill one of them or press 'Ctrl + C' from the command line).
How to debug what causes this?

**Comment by mjungsbluth** [comment]
I experienced the same problem (Running in Mono). Try running with the /diag switch. In my case it would just loop forever because it couldn't determine branch configs. The problem ist that Jenkins does by default not checkout all relevant local branches and the regexp in the branch config did not match say 'origin/develop'. I changed the branch config regex's to include a '(origin/)?' in the beginning. That fixed the immediate problem but I'm unsure as to where this will have side effects. Since the default regexp do not contain a carret character in the beginning I fail to see why it shouldn't match but longer branch names that contain the remote name.
