### ISSUE TITLE
NuGet package now requires running a project in .NET Standard/.NET Framework.  3.6.5 did not have such a limitation

### ISSUE THREAD

**Issue by stunney** [GitTools/GitVersion#1454]
In 3.6.X, all of the binaries were crunched into a single DLL (GitVersionTask.dll) during the build process.  This allowed the nuget package to be installed on Managed AND Native projects.  With the addition of dependencies into the nuspec, Native projects cannot install the package.

If not going back to re-packing the binaries into a single DLL, please find a way to work around the crappy NuGet forced limitation trying to match a target project with a development (build) dependency.

**Comment by dazinator** [comment]
Not fully understanding this. The NET desktop version of gitversiontask.dll used to have its dependencies ILMerged thats true. Now they are just included in the nuget package alongside the assembly itself. We did some testing with msbuild, and when msbuild for desktop (not dotnet cli) builds a proj file with targets that load gitversiontask assembly, it was clever enough to resolvr its dependencies from the same base bath (i.e  inside the nuget package) so in this case ILMerging them didnt seem necessary step anymore. For the dotnet cli version of gitversiontask, there is no ILMerge equivalent for the dotnetcore stack. Instead UtilPack handles resolving dependencies of the build task through a nuget restore the first time its used in a dotnet.exe build worker process.

**Comment by dazinator** [comment]
UtilPack dependency currently needs to stay as a dependency listed in the .nuspec file, even if we end up ILMerging all of the dependencies again for the desktop version. Just be wary of this. It's because we rely on UtilPack's msbuild task factory to load and execute our task now. This decouples us from the platform, but it does require that the UtilPack package is installed. The only way to ensure the utilpack package is installed, is to list it as a dependency in the nuspec. If we remove this entry, the current targets that rely on util pack task factory won't work.

With this taken into account, it would be better to understand this "native" project use case and the nuget limitation a little more. Perhaps there is another workaround.

**Comment by dazinator** [comment]
More background about that issue can be found here: https://github.com/CometaSolutions/UtilPack/issues/24
