### ISSUE TITLE
Mainline mode. increment: inherit does not seem to work

### ISSUE THREAD

**Issue by philippdolder** [GitTools/GitVersion#1531]
In my config `master` has `increment: Minor`. According to `gitversion /showconfig` feature and pull request branches have `increment: inherit` by default. But I only get `Patch` increments in feature and PR branches.

I created a reproduction repository in https://github.com/philippdolder/gitversionInheritRepro

to get the PR-merge branch on the local box you can use `git fetch origin refs/pull/1/merge:<branch_name>`

**Comment by kid93** [comment]
@philippdolder have you heard back or found a relating issue where the problem is addressed?

Thanks

**Comment by philippdolder** [comment]
@kid93 I didn't hear anything back

**Comment by Jaykul** [comment]
We had the same problem. Had to manually set the **increment** everywhere, because it's ignoring our configuration of `master`'s increment mode and "inheriting" `Increment=Patch` everywhere.

I think that `/showconfig` switch needs to _calculate_ what the actual inherited value is, and show that alongside Inherited. Ideally, with an indication of _where_ it's inherited _from_. It would have made this a lot easier to figure out...
