### ISSUE TITLE
Drop net461?

### ISSUE THREAD

**Issue by pauldotknopf** [GitTools/GitVersion#1555]
It doesn't look like we are using it for any reason, other than the ```NETDESKTOP``` define, which doesn't seem needed.

The latest libgit2sharp native binaries are targeting only netstandard, so we wouldn't be able to upgrade.

Can I PR it?

**Comment by pauldotknopf** [comment]
See https://github.com/GitTools/GitVersion/pull/1544

**Comment by pauldotknopf** [comment]
Hmm, it looks like libgit2sharp was already updated! Not sure how it worked, but I'm gonna roll with it.

With that said though, why is the net461 target needed?

**Comment by kll** [comment]
It is considered a good practice to do so, mostly for the benefit of downstream packages consuming GitVersion rather than for GitVersion running by itself.

> Using .NET Standard 2.0 from .NET Framework has some issues that were addressed in .NET Framework 4.7.2. You can improve the experience for developers that are still on .NET Framework 4.6.1 - 4.7.1 by offering them a binary that is built for .NET Framework 4.6.1.

More detail in [this section](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#multi-targeting) of the Open-source library guidance.
