### ISSUE TITLE
Sort out documentation

### ISSUE THREAD

**Issue by asbjornu** [GitTools/GitVersion#1592]
I've registered [gitversion.net](https://gitversion.net/) to host GitVersion's documentation. What's being served there is whatever is in the `gh-pages` branch. We also have the `docs` folder, which is the source of the [documentation on ReadTheDocs](https://gitversion.readthedocs.io/).

I assume using ReadTheDocs for its versioning capabilities and search is a good idea. But whatever resides within the `gh-pages` branch seems to be fairly out of date. I don't like the whole idea of a separate branch with completely different content from `master` and I think the fact that `gh-pages` hasn't been touched since 32eca24606b7202489a45c2330d7d16ac5c5edc1 (by @gep13) is enough evidence that a separate branch isn't a viable way to deal with documentation.

We have tests that verify the documentation hosted on RTD, but nothing of the sort for `gh-pages`. GitHub supports using sub-folders as sources for GitHub Pages, so I think we should start doing that. I'm just not sure what should be hosted on that site and how it relates to RTD.

@GitTools/developers, what are your thoughts?

**Comment by pascalberger** [comment]
The stuff in the `gh-pages` branch is probably from the old GitHub hosted page which was abandoned with https://github.com/GitTools/GitVersion/issues/666. 

So I think the branch is no longer required and we keep it either for historical reasons or delete it. I would be OK with the second.

**Comment by asbjornu** [comment]
Thanks for the details, @pascalberger. Not sure if it's a good idea or not, but a possible venue might be to move from ReadTheDocs to GitHub Pages. If so, gammapy/gammapy#1241 might be a useful read.

**Comment by pascalberger** [comment]
There are also other static site generators like [Wyam](https://wyam.io/) or [DocFx](https://dotnet.github.io/docfx/) which could be used if moved to GitHub pages.

If going this route, I personally prefer to have an oprhan `gh-pages` branch instead of using a sub directory to have documentation source (the Markdown files which are part of `master` branch) and documentation build output (the HTML files in the `gh-pages` branch) clearly separated and not have the source branch mixed with build output commit. But of course this is completely opinionated :)

**Comment by asbjornu** [comment]
If we're going to separate out the documentation from GitVersion's source code, I would prefer having it in a separate repository altogether and just delete the `gh-pages` branch and `docs` folder. The problem with that is keeping the documentation in sync with the code. I'm sure it's doable in a way, but we can't do it atomically in a single pull request as we can now.

**Comment by gep13** [comment]
@asbjornu the way that I tend to do documentation is inline with what I "think" you want.  I store the source files for the documentation next to the code, that way, as you are updating one, you update the other (or at least, this is the ideal).  I then use that static documentation generator, Wyam, to take those source files, and create the site.  For me, this is ultimately hosted on a `gh-pages` branch in the same repository, and served from there.  I think we can achieve something similar here for GitVersion, if that is the route that we want to go down.

**Comment by pascalberger** [comment]
I'm doing it the same way as @gep13 and avoid separate repositories to have the possibilities to make and review changes in the source and doc in one PR

**Comment by asbjornu** [comment]
Thanks for the input, @gep13 and @pascalberger! Yeah, what you describe makes sense. Wyam looks like a good fit as this project is written in .NET. Would it be possible to build something that could replace RTD and be hosted on GitHub Pages without boiling the ocean? Do you have examples of something RTD-alike we can run with?

**Comment by gep13** [comment]
@asbjornu Something could definitely be done.  The only thing that Wyam doesn't do OOTB, and if we wanted to keep it we would have to do some work, is to handle different versions of the documentation.

**Comment by asbjornu** [comment]
Right. Since that's something RTD does, versioning would be great to have, yes. That's probably something we need to do in the build process, then?

**Comment by gep13** [comment]
@asbjornu if I recall correctly, yes.  I believe that @daveaglick had a suggestion about how this "could" be done with Wyam, but I don't recall if any site/person actually put it into action or not.  @pascalberger do you remember?

**Comment by pascalberger** [comment]
I never did a versioned site or saw any site implementing it. There's an issue over at the Wyam repo for version specific API docs: https://github.com/Wyamio/Wyam/issues/356.

In our case we're only looking for version specific contextual documentation. IMHO this is not primary an issue of Wyam but more of the whole build process. We could for example either retrieve the different versions of the documentation source from from different Git tags during build. Or publish each version to a different folder and only create the latest version every time without touching the old versions.

**Comment by daveaglick** [comment]
There's two different things people mean when they say "versioned docs": versioned content and versioned API docs. The two are related, but not necessarily the same. They're certainly different from a tooling perspective. If all you're looking for is versioned content and not multiple versioned API docs, then the problem is quite a bit easier.

There's a few different ways I've seen people handle versioned docs:
* Treat all versions as a single "site" with a single build process. Versioned content is in a subfolder-per-version. Versioning the API docs is harder this way because you'd get duplicate and conflicting symbols during the compilation, so generally this approach just documents the latest API.
* Treat the versions as a "point in time" build of the same site. The docs repo always contains documentation and a build for the latest version, but is tagged in such a way that you can go back and build/publish previous versions. The output of the generation is published to different folders or hosts for each version and something like a JSON file with client-side lookup can be used to switch between versions (so that older, previously-published versioned docs can still have links to newer as-yet-unknown versions).
* Use subfolders within a single repo for each version, each one being a totally distinct "site" with it's own build process, content, etc. Use a build script to automate building and publishing just the latest and/or all previous versioned docs.

In general, @pascalberger is right - regardless of the static generator, versioning the docs is partly a process problem. Granted a particular generator can help with that (which is why there's a Wyam issue for it), but any static generator is going to be able to provide versioned docs with the right process in place and a few tricks.

**Comment by asbjornu** [comment]
Yup, I agree we should be able to fix this in the build process. One version per tag, preserving the last version in a folder, sounds like a good approach.
