### ISSUE TITLE
Merge develop into release branch, CommitsSinceVersionSource decrements

### ISSUE THREAD

**Issue by seanamosw** [GitTools/GitVersion#1632]
It seems that when we merge develop into an open release branch, with the intent of getting all new work into a release, the `CommitsSinceVersionSource` for develop decreases. Obviously this results in version conflicts.

Should we be merging develop into a release branch?
Should we rather cherry pick stuff from develop into release if we want to add work to a release?
Is this a bug?

**Comment by tpaxatb** [comment]
If you are using the gitflow paradigm, you really shouldn't be merging anything into a release branch once it has been created.  You should be cherry picking fixes back onto the develop branch.  You've basically reset your "start" point of the release to the newest merge which is why your version numbers seem wonky.

If you find you are merging things into a release branch on a release branch, then you have branched too soon.  In a normal flow situation, you would only fix critical bugs on your release branch (crashes, etc) and then either wait until the release is finished (when it is merged back into develop), or cherry-pick them back onto your develop branch.
