### ISSUE TITLE
Where the PreReleaseTag number comes from?

### ISSUE THREAD

**Issue by mniak** [GitTools/GitVersion#1646]
Running `gitversion` on my repository returns something like this: 
```
{
  "Major":0,
  "Minor":11,
  "Patch":0,
  "PreReleaseTag":"beta.1",
  "PreReleaseTagWithDash":"-beta.1",
  "PreReleaseLabel":"beta",
  "PreReleaseNumber":1,
  "BuildMetaData":117,
  "BuildMetaDataPadded":"0117",
  "FullBuildMetaData":"117.Branch.beta.Sha.3c108d170d4bb03626cf7f910c8bbea901a4e55d",
  "MajorMinorPatch":"0.11.0",
  "SemVer":"0.11.0-beta.1",
  "LegacySemVer":"0.11.0-beta1",
  "LegacySemVerPadded":"0.11.0-beta0001",
  "AssemblySemVer":"0.11.0.0",
  "AssemblySemFileVer":"0.11.0.0",
  "FullSemVer":"0.11.0-beta.1+117",
  "InformationalVersion":"0.11.0-beta.1+117.Branch.beta.Sha.3c108d170d4bb03626cf7f910c8bbea901a4e55d",
  "BranchName":"beta",
  "Sha":"3c108d170d4bb03626cf7f910c8bbea901a4e55d",
  "ShortSha":"3c108d1",
  "NuGetVersionV2":"0.11.0-beta0001",
  "NuGetVersion":"0.11.0-beta0001",
  "NuGetPreReleaseTagV2":"beta0001",
  "NuGetPreReleaseTag":"beta0001",
  "CommitsSinceVersionSource":117,
  "CommitsSinceVersionSourcePadded":"0117",
  "CommitDate":"2019-03-22"
}
```
### After the `beta` prerelease label, comes a `1` that I cannot identify where it comes from.
**Where does it come from?**

I am trying to use GitVersion on Azure Devops, but since this `1` never changes, my packages are conflicting.

**Comment by mniak** [comment]
If only I could use the `BuildMetaData` in place of this misteryous 1, I would be happy.

**Comment by tpaxatb** [comment]
It comes from a tag on the branch.  For example you are hacking away on your beta branch getting it ready for release, that beta semver should remain 0.11.0. Up until that point, you are working on 0.11.0-beta.1   When you get to the point where you are going to send that version of the build to someone, you tag that commit "v0.11.0-beta.1".  Any commits from that point on will be 0.11.0-beta.2

In other words, PreReleaseNumber is computed from the semver tags for that branch.  And note, that the semver computed for the branch must actually match the tag on the branch.  In other words, if you tagged it 0.12.0-beta.123 it will not catch it, because you are actually working on 0.11.0.  So at the point you want to expose your beta somewhere you could potentially run on the commit you are releasing:
git tag v`GitVersion /showvariable SemVer'

**Comment by dweggemans** [comment]
If I tag a release branch - without the `v` version prefix since we version without prefix - the version does not increment. @tpaxatb does this only work with the prefix?

**Comment by mniak** [comment]
Thanks. 
I understood. Maybe this could be on the documentation somewhere.

**Comment by EmilAlipiev** [comment]
> It comes from a tag on the branch. For example you are hacking away on your beta branch getting it ready for release, that beta semver should remain 0.11.0. Up until that point, you are working on 0.11.0-beta.1 When you get to the point where you are going to send that version of the build to someone, you tag that commit "v0.11.0-beta.1". Any commits from that point on will be 0.11.0-beta.2
> 
> In other words, PreReleaseNumber is computed from the semver tags for that branch. And note, that the semver computed for the branch must actually match the tag on the branch. In other words, if you tagged it 0.12.0-beta.123 it will not catch it, because you are actually working on 0.11.0. So at the point you want to expose your beta somewhere you could potentially run on the commit you are releasing: git tag v`GitVersion /showvariable SemVer'

this is not working like that starting from version 6? Is-mainline is removed and Is-main-branch also doesnt exist.
It keeps taking PreReleaseNumber calculated as number and adds as suffix like 1.0.0-25 and this is recognized as prerelease version.
How do you get the version without this PreReleaseNumber?
