### ISSUE TITLE
On nuget.org, Pre release versions of GitVersion.Commandline, the package itself, don't sort correctly.

### ISSUE THREAD

**Issue by da9l** [GitTools/GitVersion#1655]
I'd rather not go into whether nuget.org follows semver or not but...
on nuget.org, 
Pre release versions of GitVersion.Commandline, the package itself, don't sort correctly. For instance, 5.0.0-beta2-6  > 5.0.0-beta2-54.
The consequence is that if I want to install the latest pre-release of GitVersion.Commandline without specifying the exact version I get 5.0.0-beta2-6 even if there is a later one: 5.0.0-beta2-54.

See: https://www.nuget.org/packages/GitVersion.CommandLine

Would zero padding be too awful?

**Comment by da9l** [comment]
This is still happening. 
![image](https://user-images.githubusercontent.com/146797/59198567-550f5680-8b94-11e9-98c8-559179973137.png)

There are reasons to believe that there are ~400 users believing that they are using the latest version while they are not.

**Comment by wjrogers** [comment]
Looks like an attempt was made to fix this starting with package version 5.0.0-beta5.1, but this format still doesn't comply with [SemVer's pre-release numbering rule](https://semver.org/#spec-item-9):

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

If the current package numbering continues, beta10.1 will sort before beta9.x because there is no dot separating the name from the first number (i.e. the current version number should have been 5.0.0-beta.5.9).

On the other hand, it seems unlikely the project will reach a beta10.1 pre-release, and changing to beta.x.y now would create a new problem: such a version would sort before beta5.x. So probably best to stick to the partial fix currently in use!
