### ISSUE TITLE
Fix the version numbers for beta versions of GitVersion 

### ISSUE THREAD

**Issue by mikeblakeuk** [GitTools/GitVersion#1717]
Because the beta releases are not padded, they return the wrong version.
e.g. If I want latest, I get Beta3+4 instead of Beta3+35 because it's sorted A-Z!

.\nuget install GitVersion.CommandLine -ExcludeVersion -PreRelease -OutputDirectory /tools

Should it follow the GitVersion schema instead of 0035 ?

![image](https://user-images.githubusercontent.com/1986660/60173793-76fd1000-9807-11e9-98f0-8a5ecffc92a2.png)

**Comment by arturcic** [comment]
Are you in a position to make a PR?

**Comment by asbjornu** [comment]
After reading [the following blog post](https://devblogs.microsoft.com/nuget/supporting-semver-2-0-0/), [the documentation](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#normalized-version-numbers), and https://github.com/NuGet/Home/issues/1359#issuecomment-328519398, I conclude that the mistake here must be that we use `-` as a separator instead of a `.`. I believe `5.0.0-beta3.35` should be sorted as higher/newer than `5.0.0-beta3.4`. A PR to fix this would be highly appreciated. 🙏

**Comment by arturcic** [comment]
fixed in 893d6e4d5d97c04e15d8b03d8689b3a993f93baa
