### ISSUE TITLE
Azure Pipeline Task - default Config File path to GitVersion.yml doesn't work

### ISSUE THREAD

**Issue by jakubsuchybio** [GitTools/GitVersion#1782]
Regarding [Azure Pipeline Task GitVersion](https://marketplace.visualstudio.com/items?itemName=gittools.gitversion) with default values (nothing is filled by me)

In info tooltip on ```Config File``` you have:
![](https://i.imgur.com/9COnOa5.png)

**Actual behaviour:**
Default doesn't pick up GitVersion.yml. I didn't have it filled:
![](https://i.imgur.com/4I17WRG.png)
and the build resolved version to this:
![](https://i.imgur.com/uaWTR0P.png)

But when I filled ```GitVersion.yml``` into the task:
![](https://i.imgur.com/xDxKcQE.png)
then it picked it up correctly:
![](https://i.imgur.com/UX34sqF.png)

My GitVersion.yml file:
https://github.com/jakubsuchybio/Remove-Diacritics/blob/71301d017275c9d7250fbfd1a3cc58380ff8ba98/GitVersion.yml#L1-L3

**Expected behaviour:**
I expect it to pick up GitVersion.yml by default when I don't fill the task

**Comment by arturcic** [comment]
@jakubsuchybio, I fixed in 8d4f9abfe7c37d3b6554c1dbe2f30208f1da2b82. Now there is an additional checkbox that you have to check in order to specify a custom config file. In case it's not checked, it will try to use the default GitVersion.yml file. You can test it with the latest preview version of the task from here. You will have to uninstall and then install the new version to the organization.

**Comment by jakubsuchybio** [comment]
@arturcic Works like a charm!
![](https://i.imgur.com/dbT6S2s.png)
![](https://i.imgur.com/o6uVST4.png)
Thanks!
