### ISSUE TITLE
Mainline Mode; tags on feature branch commits cause exception after merge

### ISSUE THREAD

**Issue by pianomanjh** [GitTools/GitVersion#1809]
GitVersion 5.0.1
I am using mainline mode.
We will develop on a `feature/my-branch`.  Commits to this branch trigger pre-release builds of components for testing.  All successful builds tag the repo with the semver.  i.e. `12.2.1-my-branch.2+54`.  Ultimately, the feature branch is merged with no-ff to master.
When attempting to semver the master branch, GitVersion fails with message:
`System.NotSupportedException: Mainline development mode doesn't yet support pre-release tags on master`

It seems strange GitVersion would even consider tags that do not match it's tag regex configuration.

**Comment by asbjornu** [comment]
I agree the tag regex should apply here. Would you be up for submitting a PR, @pianomanjh?

**Comment by asbjornu** [comment]
Ping @pianomanjh

**Comment by ptr727** [comment]
Not stale please, this bug prevents publishing pre-release builds to github releases.

**Comment by ptr727** [comment]
Not stale please, this bug prevents publishing pre-release builds to github releases.

**Comment by ptr727** [comment]
Still happens, prevents using github actions from pushing prerelease releases.

**Comment by asbjornu** [comment]
@ptr727, we accept pull requests. I'm not using Mainline, so I have no incentive to fix this bug myself.

**Comment by andyfurniss4** [comment]
Also having this problem. I want to feature branch from master, have prerelease builds/NuGet packages available with an 'alpha' tag and then when I merge back to master I want a new SemVer increment which does not include the alpha tag. Not sure why it's even trying to add an alpha tag to master.

**Comment by stevenpollack** [comment]
I'm getting this problem, as well.

**Comment by ptr727** [comment]
> I'm getting this problem, as well.

I switched to https://github.com/marketplace/actions/nerdbank-gitversioning, works with prereleases and releases.

**Comment by asbjornu** [comment]
If you have all of these branches, then why are you using `mode: Mainline`? `mode: Mainline` is mostly for repositories that use trunk based development, where every branch is squashed into a single commit on `main` and where branches doesn't really exist other than ephemerally, usually only locally, are extremely short-lived and does not in any shape or form need versioning since they aren't going to be released or deployed anywhere.

If you want versioned branches other than `main`, don't use `mode: Mainline`.
