### ISSUE TITLE
NuGet package for .NET Core 3.0 executables

### ISSUE THREAD

**Issue by matkoch** [GitTools/GitVersion#1854]
More than often I'm lost when reading about new prerelease packages here, but unable to find belonging packages on nuget.org.

The issue about .NET Core 3.0 (`It was not possible to find any compatible framework version`) seems to have been addressed. Yet, which package contains the fix?

**Comment by asbjornu** [comment]
The problem might have been fixed in #1849. If you look at the latest commit in that PR and click the green checkmark ✔️ besides the commit ID, then click the AppVeyor build and go to its [Artifacts](https://ci.appveyor.com/project/GitTools/gitversion/builds/27997432/artifacts), you'll find the build artifacts that correspond to the PR. From there you can download whichever variant of GitVersion you'd like.

You can also find the latest pre-release version published to NuGet.org with a release date newer than the merge date of the PR you want.

**Comment by matkoch** [comment]
Which package? https://www.nuget.org/packages/GitVersion.CommandLine.DotNetCore/ ?

**Comment by asbjornu** [comment]
@arturcic, why aren't there any newer versions of `GitVersion.CommandLine.DotNetCore` than `5.0.2-beta1.71`?

**Comment by arturcic** [comment]
@asbjornu, that's because the global tool now can be installed as local tool as well, making the GitVersion.CommandLine.DotNetCore obsolete.

**Comment by matkoch** [comment]
@arturcic that contains an exe?

**Comment by arturcic** [comment]
If you need the "exe" version you might need the GitVersion.CommandLine nuget package

**Comment by matkoch** [comment]
No I don't, I just had the wrong package. It's a bit of a .... let's say I'm overwhelmed with possbilities.

The `GitVersion.Tool` package is 22mb. Sounds quite a lot for "just" calculating a version number. Is that really necessary?

**Comment by arturcic** [comment]
The think is that we use a native library that has implementations for several linux distros as well as macOs and windows. All of them make the size bigger. The GitVersion itself is really small

**Comment by matkoch** [comment]
times 2 for netcore2.1 and netcoreapp3.0

**Comment by arturcic** [comment]
that is true, we'll need to think about reusing if possible the same native binaries

**Comment by gep13** [comment]
>@arturcic said...
that's because the global tool now can be installed as local tool as well, making the GitVersion.CommandLine.DotNetCore obsolete.

Would it make sense to mark it as such on nuget.org, now that NuGet.org has the ability to mark a package as deprecated?

As an example, have a look at the banner on this package:

https://www.nuget.org/packages/Cake.Tfs/

**Comment by arturcic** [comment]
Unfortunately Gary I don't think I have access to the nuget.org. I have only the API_KEY. Can you help with that?

**Comment by gep13** [comment]
@arturcic you should now have all the access that is required on NuGet.org.  Let me know if there is anything else I can do to help.
