### ISSUE TITLE
[Improvement] Chocolatey package 'gitversion' should point to 'gitversion.portable'

### ISSUE THREAD

**Issue by pauby** [GitTools/GitVersion#2193]
**Is your improvement request related to a problem? Please describe.**
It appears that the 'gittools' team  maintain the Chocolatey package 'GitVersion' which is makred as 'Obsolete'. Given there is no other gitversion package, I would suggest it points to the 'gitversion.portable' package as it is causing confusion.

## Detailed Description
Have the 'gitversion' Chocolatey package have 'gitversion.portable' as a dependency (and therefore act as a 'virtual package'.

## Context
If you install the gitversion package you get an obsolete version that is simply a text file.

**Comment by arturcic** [comment]
@gep13 what do you think about?

**Comment by gep13** [comment]
@arturcic I was actually talking privately with @pauby about this...

What is the current state of the GitVersion package on NuGet?  https://www.nuget.org/packages/gitversion

It doesn't look like it is currently being updated.  Is it now deprecated?

I think the original reason that we stopped updating the GitVersion Package on Chocolatey was because we had a package named GitVersion being pushed to NuGet.  If that is no longer the case, then creating a meta package on Chocolatey makes sense to me.

**Comment by arturcic** [comment]
Agree, let's deprecate the `GitVersion` package and is there anything we should do in our build scripts to have the metapackage created?

**Comment by gep13** [comment]
Yes, we will need to modify the build script to include the creation of that package.  I can try and take a look at this at some point, but it won't be immediately.

**Comment by ericnewton76** [comment]
2 years in the future... `choco install GitVersion` installs 1.0.0.1   lol

**Comment by gep13** [comment]
@ericnewton76 that is a really helpful comment to leave on this issue! Thanks for sharing!
