### ISSUE TITLE
[Improvement] Document Git repository requirements

### ISSUE THREAD

**Issue by asbjornu** [GitTools/GitVersion#2194]
Seeing how getting GitVersion to work in different CI servers (Jenkins seems particularly problematic) is a recurring problem, it would be great if we documented GitVersion’s requirements for successfully generating a version number such as:

1. An unshallow clone.
2. An existing local `master` branch.
3. Possibly an existing local `develop` branch (for GitFlow).
4. Should be [switched](https://git-scm.com/docs/git-switch) to a named, existing branch pointing to the commit being built (i.e. no detached `HEAD`).
5. `Git_Branch` as an available environment variable.
6. If using a `GitVersion.yml` file, that file should be checked out otherwise it won't be found by GitVersion and default config will apply.

Possibly related issues: #1335, #2180, #2118, #2115, #1857, #2233.

**Comment by kwaazaar** [comment]
Sounds good. And maybe clear examples for the different CI servers.

I'm new to GitVersion, but I see all dev-teams here use different GitVersion.yml files because they're struggling with the options, resulting is messy version numbers and unusable versionnumbers for example for Docker images.

Versioning is important and must be done right. But it should be just a small, one-time set-up task you never have to look at anymore. That's not my experience so far.

(we use Azure DevOps)

**Comment by asbjornu** [comment]
@kwaazaar, if you use one of the supported Git processes, such as [Git flow](https://nvie.com/posts/a-successful-git-branching-model/), the process itself will take care of the versioning and no `GitVersion.yml` should be required. It's only when you have an undefined or custom process versioning becomes difficult, regardless of whether you use GitVersion or something else as the source of the application's version number.

**Comment by dazinator** [comment]
I wonder if... shallow fetching can actually be used with certain branches.

For example, if we use the last tag on master or develop as a source, then it might be possible to only fetch master or develop branches back as far as the last tag. Just a thought.

**Comment by asbjornu** [comment]
Hm, yeah, that's an interesting thought. `git fetch --depth 1 origin tag <tag-name>` should suffice for most, I assume. We would have to know the name of the tag to fetch, though.

**Comment by dazinator** [comment]
@asbjornu I'm not really familiar with shallow cloning. But conceptually I think what we'd need to do (could be mistaken) is fetch all commit history from current HEAD back to the latest tag - so that if current HEAD isn't tagged, we can still walk the commit history to find the previous commit with the tag and use that as the version source, and then each commit after that adds to the commit count that we use to calculate the final version (plus all other logic that we do). I think fetching history further back than that last tag is probably irrelvent?

Is that what `git fetch --depth 1 origin tag <tag-name>` does - because my interpretation of that was that it was just going to fetch the specified TAG as HEAD, and only include that commit - so would be missing all the newer commits..

I think if we wanted to enable this we'd need someway of determining what `depth` should be in this command: `git fetch --depth X` in order to fetch only as far back as the commit with the last tag.

I'm not sure if there is any clever way to calculate that - however a quick search yielded this:

> In order to find the latest Git tag available on your repository, you have to use the “git describe” command with the “–tags” option: https://devconnected.com/how-to-list-git-tags/#List_Remote_Git_Tags

**Comment by dazinator** [comment]
Another thought on this requirement
> 4. A named, existing and checked out branch pointing to the commit being built (i.e. no detached HEAD).

Wondering if we need the branch checked out, or if we only need the GitVersion.yml file checkout out (if used).

**Comment by asbjornu** [comment]
It's not about files, but about Git history. In some calcuation strategies, GitVersion needs the history of the current branch at least up to the commit it was branched out from (typically) `develop` or `master`.

**Comment by dazinator** [comment]
> A named, existing and checked out branch

If files aren't needed should "checked out" be a requirement. The only file I can think might be needed is gitversion.yml and that might not be used by everyone so is optional in that sense. If used its possible to do a single file checkout, which might be preferable for jobs that don't build sources.

**Comment by asbjornu** [comment]
Perhaps `checkout out` isn't the right terminology. What I mean is that the branch being built should also be the one Git is [switched](https://git-scm.com/docs/git-switch) to.

**Comment by dazinator** [comment]
@asbjornu - yup that makes more sense.

**Comment by dazinator** [comment]
Would requirement 6) be:

- If using a GitVersion.yml file, that file should be checked out

**Comment by asbjornu** [comment]
No, we aren't checking out any particular files, the normalization is just to ensure we have history and relevant branches in place. Requirement 6 makes sense, yes.

**Comment by dazinator** [comment]
Ok cool - added that. Can't think of anything else!

**Comment by dazinator** [comment]
I lied there was one more thing ;-) 

> Git_Branch as an available environment variable.

I'm not setting GIT_BRANCH environment variable anywhere and I am using the azure-pipelines task without any problems. Is this a requirement - or is this only required in some circumstances?

**Comment by asbjornu** [comment]
I think it's required only in some circumstances, but we haven't documented which. It might be that reuirement 4 and 5 are mutually exclusive.

**Comment by dazinator** [comment]
Nice one @asbjornu !
