### ISSUE TITLE
The BREAKING_CHANGES.md doesn't seem to be getting updated

### ISSUE THREAD

**Issue by warlock2k** [GitTools/GitVersion#2230]
Are there any breaking changes from 4.0.0 to 5.2.4?

**Comment by asbjornu** [comment]
Sorry, but this seems to have been forgotten. Thanks for pointing it out!

Yes, there are breaking changes between 4 and 5, otherwise we wouldn't have incremented the major version. Meanwhile `BREAKING_CHANGES.md` is out of date, taking a scroll through the [5.0.0 Milestone](https://github.com/GitTools/GitVersion/milestone/13?closed=1) might give you some ideas. #1541 seems to be the most important breaking change going into version 5.
