### ISSUE TITLE
[Feature] Calculate version number from merged release/hotfix branch when commit message have no version info

### ISSUE THREAD

**Issue by pi3k14** [GitTools/GitVersion#2242]
**Version 4.0.0 changed parsing of commit messages.**
Pre 4.0.0 there was a generic parsing of commit messages to get version number, this changed to use templates for specific build systems. With Azure DevOps this became problematic as the standard PR commit message is in "constant flux".

## Detailed Description
Please add a fallback mechanism that get the version number from the branch name of last merge of release/hotfix into master/develop if no version number can be found in commit message.
Eg. hotfix/1.0.1 is merged into master with commit message "Merge of hotfix/1.0.1 to master" (this doesn't match any standard message format) the version for master should be 1.0.1.

## Context
In addition to fix problems with varying commit message formats this would also fix "problematic users" that can't write a correct PR Merge message. Strange branch names will always be corrected, given that you follow GitFlow.

**Comment by richardleesimpson** [comment]
If I may piggyback off this open issue, I believe this is the problem I'm running into as well.

When merging pull requests in Azure Repos, the default merge message is currently "Merged PR [number]: [title]". There's no way I know of to change that default, and also no way to prevent the one completing the PR from overriding the message. Short of expecting everyone to remember to manually update the message field, this makes it likely that the CI pipeline triggered by the merge commit will calculate the wrong version. For example:

1. Make changes to develop; GitVersion calculates version 1.4.0-alpha0010
2. Branch from develop off to release/1.4.0; GitVersion calculates version 1.4.0-beta0001
3. Merge release/1.4.0 into master with message "Merged PR 30: This is a title"; GitVersion calculates version 1.3.1 instead of 1.4.0

Is there a way to just pull the version from the release branch name? If not, is there something else I'm missing here?

**Comment by asbjornu** [comment]
The branch name is already a source of version information, @richardleesimpson. The problem is that branch names as the source of anything is pretty much useless over time, since branches are volatile and are deleted, usually after they are merged.

So as soon as the release branch has had its affect on the version calculation, it is deleted, making it very difficult for GitVersion to calculate the same version number again from the same source, since the source is gone.

**Comment by pi3k14** [comment]
That the release branch is deleted is in fact no problem, usually you tag master with the release number when merging in a release branch. Which GitVersion uses for later version calculation.

Re. 'branch name is already a source of version information', can you (@asbjornu) give a reference to source code where this is performed? Because I was searching for such when investigating this feature request, and could not find any.

@richardleesimpson defining
`merge-message-formats:
    devops: (?<SourceBranch>.+)`
in GitVersion config would help getting version info from merge message as long as there is any reference to the branch name there. It seems like you also have to configure hotfix as release branch for this to work there.

**Comment by asbjornu** [comment]
@pi3k14, given a `git tag`, the release branch name isn't necessary anymore, correct. Not everyone follows Git Flow to the letter, though. Here's the code that extracts version number from a branch name:

https://github.com/GitTools/GitVersion/blob/5330bbb2b93571c2e6ea8b91e2758798b28e52e4/src/GitVersionCore/VersionCalculation/BaseVersionCalculators/VersionInBranchNameVersionStrategy.cs#L48-L60
