### ISSUE TITLE
Tagged commit is not taken as base version

### ISSUE THREAD

**Issue by hana26** [GitTools/GitVersion#2309]
I am implementing GitVersion for a repository that contains this particular branch: rel-19.1.1 which was an old release branch. However our versions have changed since then and we are now at 5.11.0 and I want this to be the base version going forward. I tagged the commit in which I added GitVersion as a build step with 5.11.0. However when this branch is built, it is still considering 19.1.1 as the base and using that for subsequent increments. How do I enforce GitVersion to use 5.11.0?

In the documentation it says that if the commit is tagged, then that version is accepted as the base version and the next steps aren't called: https://gitversion.net/docs/more-info/version-sources & https://gitversion.net/docs/more-info/how-it-works

**Comment by asbjornu** [comment]
I would expect GitVersion to not consider `rel-19.1.1` as a release-branch, as that should be the default since version 5 (with #1541). However, you can try to configure the `rel-19.1.1` branch to not be a release branch by declaring it as not being a release branch with [`is-release-branch: false`](https://gitversion.readthedocs.io/en/latest/configuration/#is-release-branch).

**Comment by hana26** [comment]
Thanks @asbjornu! There was another branch called release/19.01, it was probably taking that into consideration? 
I was able to solve this issue by adding a tag to my commit with 5.11.0 and since I made a change to GitVersion.yml, I think it cleared the cached values and recalculated right?  It's what I understood from #798 and #808

**Comment by asbjornu** [comment]
Yep, that sounds right @hana26. Adding a tag is usually the best way to control the version number GitVersion uses for its calculations.
