### ISSUE TITLE
No documentation at how to get started with the NuGet Package

### ISSUE THREAD

**Issue by YahArt** [GitTools/GitVersion#2563]
# The Problem
I would like to use the GitVersion NuGet Package (https://www.nuget.org/packages/GitVersion.Core/). However when switching to the documentation (https://gitversion.net/docs/usage/nuget-library) there is not a lot of information at how to get started.

# My Goal
My Goal is to use GitVersion in order to get the semantic version as well as a few other things for a git repository. Essentially I would like to call a method and get the same output back as if I were calling the GitVersion.exe with no arguments. The response of calling GitVersion.exe with no arguments is a json which would be perfect for my purpose. However I would like avoid having to install the GitVersion.exe itself. Therefore I would like to use the NuGet Package itself.

Perhaps this is also no the right approach for this kind of thing and it should be done in a different way.

**Comment by asbjornu** [comment]
If it's possible, I would recommend using `gitversion.exe` and taking the output JSON instead of sourcing the library. The library and its API is not officially supported and may break between minor versions since it's the API of the MSBuild Task, the `.exe` and the syntax of `GitVersion.yml` we consider the official, public API of GitVersion.
