### ISSUE TITLE
[Bug] MacOS gitversion cli

### ISSUE THREAD

**Issue by EdwardBlair** [GitTools/GitVersion#2839]
**Describe the bug**
Naively following install [instructions](https://gitversion.net/docs/usage/cli/installation) for MacOS

`brew install gitversion`

`gitversion --help`

> Unhandled exception. GitVersion.WarningException: Could not parse command line parameter '--help'. If it is the target path, make sure it exists

## Expected Behavior
`gitversion --help` should work, similarly `gitversion -h`

## Actual Behavior
Crash 😢 

## Steps to Reproduce
See above

## Context
I was trying to use gitversion on MacOS

Additionally,

`dotnet-gitversion`

> command not found: dotnet-gitversion 

It should be made more clear in docs that if installing through homebrew interface is through `gitversion` not `dotnet-gitversion`

## Your Environment

- Version Used: 1.0.0
- Operating System and version (Windows 10, Ubuntu 18.04): MacOS BigSur 11.4

**Comment by EdwardBlair** [comment]
`executable -help` seems unutual to me, isn't this normally the same as `executable -h -e -l -p`?

**Comment by asbjornu** [comment]
> `brew install gitversion`
> 
> `gitversion --help`
> 
> > Unhandled exception. GitVersion.WarningException: Could not parse command line parameter '--help'. If it is the target path, make sure it exists
> 
> ## Expected Behavior
> 
> `gitversion --help` should work, similarly `gitversion -h`

The correct argument is `-help`, not `--help`. We know the command line interface is, which is why we're going to completely rewrite it in version 6. See #2275 for details.

> Additionally,
> 
> `dotnet-gitversion`
> 
> > command not found: dotnet-gitversion
> 
> It should be made more clear in docs that if installing through homebrew interface is through `gitversion` not `dotnet-gitversion`

".NET Global Tool" and "Homebrew" have different headers in [the documentation](https://gitversion.net/docs/usage/cli/installation). Doesn't that make it clear that what comes after the header belongs to the header? How would you describe this differently?

<img width="996" alt="Installing GitVersion" src="https://user-images.githubusercontent.com/12283/131997257-64ba58af-12c0-46dd-a7d7-85950e595aad.png">
