### ISSUE TITLE
Linux Installation Support

### ISSUE THREAD

**Issue by DJViking** [GitTools/GitVersion#2895]
A Linux installation should be added,
https://gitversion.net/docs/usage/cli/installation

The only option for Linux is docker, which is not an option really. We have our own docker images we use on Jenkins.
Also we need to use the tool without docker on Linux computers for our developers.

It would be then usefull to have installation with an RPM.

**Comment by arturcic** [comment]
Agree, we need to update the docs to include the Linux usage
Currently the option we have is to use the `tar.gz` artifacts from the [release page](https://github.com/GitTools/GitVersion/releases/tag/5.7.0). If you have the time and the wish, you could help us with a PR to update the documentation.

As for support of RPM (or any other linux package format). Unfortunately I do not have the knowledge how to create rpm/deb packages or the way delivery channels work. So if you could help with that, you are welcome, at least for now we do support only the `tar.gz` (we do test the`tar.gz` in different distros in docker)

**Comment by DJViking** [comment]
I could not find any instructions how to build this project on Linux.
I might take a look how to (if possible) for this package to produce an RPM for Linux.

**Comment by arturcic** [comment]
> I could not find any instructions how to build this project on Linux.

If you have dotnet sdk installed on linux, it's as simple as dotnet build GitVersion.App.csproj (with some additional arguments)

**Comment by arturcic** [comment]
I think @asbjornu had similar issues building from source for homebrew, maybe he can give some advices

**Comment by asbjornu** [comment]
My problems wrt. the Homebrew formula was mostly to get the .NET SDK itself to build on Linux and macOS. You can read the discussion in https://github.com/Homebrew/homebrew-core/pull/60929 (and all the linked discussions such as https://github.com/dotnet/source-build/issues/1744) to get a feel of what I had to go through in order to get that working.

But now that it is working and both the `dotnet` and `gitversion`formulae seems to be upgraded automatically as new versions of .NET arrives (see https://github.com/Homebrew/homebrew-core/pull/85860 and https://github.com/Homebrew/homebrew-core/pull/83486), I don't think any such problems should exist anymore.

What problems are you experiencing around building on Linux, @DJViking?
