### ISSUE TITLE
Alpha Version Decrements

### ISSUE THREAD

**Issue by ppi-kosipenko** [GitTools/GitVersion#3354]
**Describe the bug**
When develop branch is merged into an existing release branch, merge base is reset and commit count (PreReleaseNumber) decrements for develop branch. This is a disaster, because nuget package version logic breaks.

I found similar request without an answer, so we are not alone: https://github.com/GitTools/GitVersion/issues/2170

## Expected Behavior
PreReleaseNumber should never decrement

## Actual Behavior
PreReleaseNumber decrements, forexample: before merge: 1.1.0-alpha.11, after merge:  1.1.0-alpha.2

## Your Environment

- Version Used: GitVersion.Tool 5.12.0 x64
- Operating System and version (Windows 10, Ubuntu 18.04):
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by HHobeck** [comment]
Please see this discussion [Prevent decrementation of versions on the develop branch](https://github.com/GitTools/GitVersion/discussions/3177). Merging from develop to release branch should be avoided.

**Comment by ppi-kosipenko** [comment]
I understand that it is not the best practice to merge develop into release. It doesn't happen routinely, it is an exception. The end result is that nuget version string decrements and there seems to be no solution to address it. Telling people not to do it is not a solution...

**Comment by HHobeck** [comment]
> I understand that it is not the best practice to merge develop into release. It doesn't happen routinely, it is an exception. The end result is that nuget version string decrements and there seems to be no solution to address it. Telling people not to do it is not a solution...

If you facing this problem that the version needs to be always go up (because of technical or regulatory reason)  I pointed out different solutions how to workaround this problem:
- Cherry Picking / Squash merge from develop to release branch
- Cancel the release and go to the next version
- Work with feature branch (created from master) and merge it from feature -> develop and feature -> release branch and keep the feature branches until they have been released

Never mind if you have other ideas how to do it better please feel free and contribute.
