### ISSUE TITLE
Command line args

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#428]
Just wanted to discuss while 3.0 has not been released.

Is it worth looking to see if we can improve the command line usage? There are a bunch of better parsing libraries and conventions like `-s` `--short` which git uses which could make the usage nicer.

We could to try keep compatibility have a translation to start which translates the command line args as they are now into the new args. Help will only show the new args.

What does everyone think? Is it worth investigating or not?

// @andreasohlund @SimonCropp @gep13 @GeertvanHorrik

**Comment by GeertvanHorrik** [comment]
I think it's definitely worth investigating. It saves the code having to parse itself, it automatically supports /, -, -- and short and long codes. However... I know that it might also look like a big dependency. I don't care about it, but I know others do.

Maybe not for 3.0, if we are adding command line variables, it can be a smooth transition (add -u for -url, etc). We need to carefully thing this through instead of hurrying because 3.0 has to be released.

**Comment by asbjornu** [comment]
I think the current command line syntax in GitVersion is a mess (sorry for being frank), so cleaning it up to something a bit more conventional and familiar would be highly appreciated! :smile: 

If the dependency can be made on a source code level (and not as a NuGet binary reference), I'm all for it. Perhaps add it as a git submodule?

**Comment by GeertvanHorrik** [comment]
We are aware of this ;-)

We are trying to find a set of commands that we can re-use amongst all tools. This way, no matter what tool you use, it should be very easy to get used to any tool you would like to use. It's still on the agenda.

**Comment by JakeGinnivan** [comment]
Yeah, need to get v3 out the door. Then look at v4 for this sort of breaking change. Need to figure out how we could do some sort of compatibility mode to read legacy command lines and convert to the new one.

**Comment by asbjornu** [comment]
I agree that v3 should be shipped without this change. If the new command line argument syntax can be implemented in a backwards compatible way, it can be released as a minor v3 bump too; no need to wait for v4.
