### ISSUE TITLE
GitVersionTask should fail when it is unable to mint a version number

### ISSUE THREAD

**Issue by asbjornu** [GitTools/GitVersion#512]
When GitVersionTask is unable to generate a version number (due to missing `GITVERSION_REMOTE_PASSWORD` and `GITVERSION_REMOTE_USERNAME` environment variables, for instance), it outputs a load of warnings but then exits in a way that makes TeamCity think the build succeeded, continuing to the next build steps and eventually publishing a NuGet package with the version number `0.0.0.0`.

Is it possible to have the MSBuild task to err somehow when it is unable to generate a version number at all?

**Comment by SimonCropp** [comment]
this is actually done on purpose. there are many scenarios where u dont want to ti break. for example someone has downloaded your project as a zip, ie not using git. Do you really want to stop these people from compiling?

**Comment by asbjornu** [comment]
In some projects, a DLL with no version number might be desirable. In others, it might be undesirable because it leads to support nightmares. "Which version are you using?" is a pretty standard first question to ask when someone has problems. If the project uses error reporting services like [Sentry](http://getsentry.com/), reported errors will be pretty meaningless without a proper version number attached to them. Projects pushed to NuGet will are also no-go without a proper version number.

So it would be nice to at least force the MSBuild task to err if it is unable to create a proper version number. Would it be possible to add a switch for this somehow? A property in the project file somewhere, perhaps?

**Comment by SimonCropp** [comment]
wouldnt "treat warnings as errors" have the same result?

**Comment by distantcam** [comment]
The plan is to change GitVersion to throw warnings or errors depending on the circumstances.
- Errors for anything the user can fix easily (duplicate version attributes, missing environment variables, bad config file)
- Warnings for things that are not easily fixed (GitVersion bugs, could not determine repo version because it's a detached head, or missing branches, etc.)

The reason for this is that when GitVersion fails the only way to move forward is to remove GitVersion, which is a pain to do.

If you still want to fail a CI build you can create a CI config for your project and turn on "treat warnings as errors" like @SimonCropp said. But hopefully soon this won't be an issue.

**Comment by asbjornu** [comment]
@SimonCropp There's a great chance that there's other warnings in the project. I don't think that's a viable solution. @distantcam Sounds good. Thankfully, it's usually only during initial setup or reconfiguration that GitVersion fails to create a version number, so it doesn't happen very often.

**Comment by JakeGinnivan** [comment]
Anyone want to pick this up? :)

**Comment by asbjornu** [comment]
Closing this as it's basically a duplicate of #504 and since it hasn't received any attention since 2015, we can just pick this up again whenever someone has the time to submit a PR.
