### ISSUE TITLE
Team Build Usage Documentation

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#518]
Investigation and documentation of how to use GitVersion with Team Build. I assume that Dynamic Repositories are the way to go. If it is possible to add first class support by calling back into TFS and creating variables and such then lets create another task to do that.

**Comment by anobleperson** [comment]
*Background* I looked at creating a server build for TFS, but quickly found that it required a username/password in order to access the git repo.  TFS pulls the source onto the machine and then runs the build script independently.  we never see the credentials for the git repo, so the normal mechanism won't work.  I had a look at dynamic repos, but again that requires username/password which would need to be checked into the source control or somehow stored in a way that is accessible to others, so that didn't seem great.   The current solution was to expose setting of the untracked branches, which has been working for us, but is starting to get a bit slow.  Another interesting feature of TFS is that it only checks out the default branch locally, and then checks out the required version from the commit id, so GitVersion always thinks it's in a detached head mode unless we turn on untracked branches.

*Discussion* There is always the solution of using untracked branches to fall back on, but I wonder if there is a way to just convert remote branches to local branches without having to have the credentials?  It also seems like the server build always tries to normalise the branches, which won't work of us.  I'm sure there are a bunch of other solutions I haven't thought of as well.

**Comment by JakeGinnivan** [comment]
This is all sorted now and docs have been updated. This is for build vNext, not the old Team Build though. That said, the updates to make VSO build work will make it easy for someone to update team build if they wanted. but TBH I can't see why you would use the old build system..

**Comment by johnkattenhorn** [comment]
This is so awesome! I'm swapping out my old build stuff and checking this out today! Thanks so much to everyone involved!

**Comment by JakeGinnivan** [comment]
I have not pushed 3.1 yet, hopefully in the next day or two. But feel free to grab the builds from https://ci.appveyor.com/project/GitTools/gitversion/build/artifacts and give us some feedback :)

**Comment by johnkattenhorn** [comment]
Sounds good, I'll let you know how I get on.

**Comment by johnkattenhorn** [comment]
Oh and while I’m in CI mode this afternoon I’ll *try* to crank out a custom task to Spilt out Octopus Pack so we can go something like :

GitVersion
Build
Test
Package
Release

With this work I think we have enough bits in the community to do this now. I’ll report back tonight.
