### ISSUE TITLE
BuildMetaData and FullBuildMetaData wrong?

### ISSUE THREAD

**Issue by o-o00o-o** [GitTools/GitVersion#559]
I'm a new user of GitVersion but it seems to me that a couple of the variables are not right according to my understanding of SemVer.. I'm confused as I can't see this bug already listed but it seems so glaring so I wonder if I have misunderstood something.

My InformationalVersion right now is:

2.7.0-QDO-1269-NewBambooBuild.72+Branch.feature/QDO-1269-NewBambooBuild.Sha.c52382e39adb2946a2de8d40b6936b9d8baab3ca

I would expect the main 5 parts of the SemVer to be available as a basic requirement. I can get Major,Minor,Patch and PreReleaseTag completely fine. 

But I cannot simply get the 5th part which I understand is "Build Metadata" from semver.org.

My BuildMetaData and FullBuildMetaData look like the following:

  "BuildMetaData":72,
  "FullBuildMetaData":"72.Branch.feature/QDO-1269-NewBambooBuild.Sha.c52382e39adb2946a2de8d40b6936b9d8baab3ca",

Neither seems correct. "72" is part of the PreReleaseTag (this should probably have it's own distinct variable as it relates to the number of commits since the last major.minor.patch. version e.g. "UnversionedCommits")

Full BuildMetaData surely shouldn't have "72." in it as 72 is not build metadata, it is PreRelease? I would have expected FullBuildMetaData to be everything after the + only?

Of course I could regex InformationalVersion to get the parts but it seems wrong that I would have to.

**Comment by JakeGinnivan** [comment]
This looks like a bug in a new feature in v3, continuous deployment.

Commit counting *is* part of build metadata, because committing something does not change the SemVer. Only releases should change the SemVer. The continuous deployment option changes this and breaks the contract of SemVer which says that only one number should increment each release and all lesser components reset to 0.

The bug is simply we were not clearing the commit count properly when we overwrote the pre-release version.
