### ISSUE TITLE
Version numbers are off by one when merging to master

### ISSUE THREAD

**Issue by sunsided** [GitTools/GitVersion#639]
Maybe I'm just getting this wrong, but here's my problem. I'm using GitFlow with SmartGit and GitVersion as an MSBuild task in VS2015 (except for TeamCity, where it is actually a separate step). Everything works up to the point where I create a release branch, say `release/0.2.0`. In this branch I'd update the README, CHANGELOG, etc. and end up with commit, say, SHA `1385ca96`. I then instruct SmartGit to finish the release. At this point the following happens:

On the `release/0.2.0` branch (at SHA `1385ca96`) SmartGit creates a tag `0.2.0` and pushes it to origin. It then merge-commits (`-no-ff`) `release/0.2.0` branch onto `master` (creating SHA `69031253`) and `develop` (SHA `3830dd54`) and pushes both.

When I now build the project, GitVersion determines the following version:

* on `develop` it's `0.3.0-unstable.X` (which I expect, since the next version is presumably no hotfix)
* on `master` it's actually `0.2.2`, which is not what I tagged.

I assume this is because the tag is technically one commit *before* the merge to master.

**Comment by JakeGinnivan** [comment]
Yeah, GitFlow says to merge to master then tag master which is the scenario we support.

That said you should be able to build the 0.2.0 tag to get your stable release?

**Comment by sunsided** [comment]
Probably works, just not with the default dialog box of SmartGit. I agree that's a bug in SmartGit and will report that there, however I do think GitVersion should be flexible here (following the robustness principle).
My reasoning here: Since there must not be any commits on master other than releases, why is GitVersion incrementing the version manually on the `master` branch in the first place when a tag was just given one merge commit ago?

**Comment by sunsided** [comment]
Just wanted to share what the SmartGit support told me: They're going to fix this behavior in the next version, however their behavior is intentional as nvie's implementation [over here](https://github.com/nvie/gitflow) (the default?) does it exactly like that, i.e. tags the release branch. There are multiple [pull](https://github.com/nvie/gitflow/pull/428) [requests](https://github.com/nvie/gitflow/pull/355) correcting that as well as a bunch of open tickets, however as it stands there seem to be two standards.

**Comment by Martaver** [comment]
I'm using SmartGit 7 and found exactly the same problem I'd name a release, say, 0.17.0 in SmartGit and GitVersion would spit out 0.17.1 as the version for the master commit. I disabled SmartGit's auto-tag to get rid of the misplaced release tag, and the master branch built fine as version 0.17.0... but now the problem is that my develop branch doesn't increment minor. It just continues as 0.17.0-unstable0001, unstable0002 etc... in the old version, this would just increment to 0.18.0-unstable no problems...  Is this a SmartGitism as well?

**Comment by sunsided** [comment]
Hum. The versioning is done by GitVersion, so I'd assume *that one* is not Syntevo's fault.

**Comment by Martaver** [comment]
I'm so lost amongst the standards with GitFlow... everyone seems to have their own interpretation of it. I'd love to stick with GitVersion as the bible and just pester Syntevo to make SmartGit compatible, but until then another solution would be good. 

I actually think the develop branch was being set to 0.17.0 because the previous tag on the develop branch was 0.16.0... from that point of view it makes sense, because I skipped a version. Still, I think GitVersion should be versioning develop from the last 'master' commit...?

**Comment by sunsided** [comment]
Just to rule out the obvious, you have the `0.17.0` tag on `master` and back-merged `master` to `develop` from there? If so, then I'd expect `develop` to be `0.18.0-unstableXXXX` after that as well.

**Comment by Martaver** [comment]
Actually, right now, I still have auto tagging disabled.

Previously, I had SmartGit's auto tagging enabled for releases and I would
get two commits - the new merge commit into master created by finishing the
release in SmartGit and the original commit from the release branch, which
stays on develop. SmartGit would tag the original commit, on the develop
branch.

The net result of this would be that if I created a release named
'release/0.18.0' and finished it, GitVersion would give me 0.18.1 as the
master version and 0.18.0-unstableXXXX as the develop version. Which is wak.

**Comment by JakeGinnivan** [comment]
I agree we should support SmartGit as is. We can only add support for scenarios as we see them.

The best way forward is to submit a few failing tests, this will outline the flow and what you expect. I can then try and see if we can make them pass without breaking the other scenarios we know about.

**Comment by Martaver** [comment]
Hmmm, I could set up a sample gitflow repo with a few commits from SmartGit
7.

The thing is SmartGit is kind of silly with it's out-of-the-box
functionality too, since it suggests default names for Release branches
such as release/Release-1 - then if auto tagging is enabled, it takes the
commit with the same name 'Release-1'. I usually rename them to
release/0.18.0 or whatever new minor version we're releasing.

The odd thing is, if I create a hotfix in SmartGit it'll suggest the
correct incremented patch version based on the last tag correctly, e.g. it
suggests 0.18.1 as the branch name straight up.

Not sure what the best way to tackle that is... sounds like SmartGit should
be suggesting the right version numbers.

**Comment by Martaver** [comment]
*tags the commit with the same name

**Comment by JakeGinnivan** [comment]
Have a look at our other release tests - https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore.Tests/IntegrationTests/ReleaseBranchScenarios.cs

You need to replicate what SmartGit actually does in a simple test repository. If you need a hand let me know

**Comment by Martaver** [comment]
Ok cool. I'll set it up with branch names and tags that Smartgit recommends
out of the box and we can go from there.

**Comment by sunsided** [comment]
Any update?

**Comment by Martaver** [comment]
Heya,

Yeah I meant to get onto this, but then when I downloaded the new version
of SmartGit, they seem to have made some fixes to the way they number their
release and hotfixes - gitflow versioning seems to be much smoother now. I
haven't gone deep to make sure they're perfect, but if you haven't already
- check it out?

**Comment by JakeGinnivan** [comment]
Bump, @sunsided @Martaver 

Is this still an issue, did you want to submit a PR with the issue so we can look at fixing?

**Comment by sunsided** [comment]
I was waiting for @Martaver's move. :grin: According to Syntevo, that issue was fixed in SmartGit 7.1 preview 10 as of January 14th, 2016.

**Comment by Martaver** [comment]
Hey guys, I haven't been having any problems with SmartGit since their
update a while back. So no complaints from my end!

**Comment by JakeGinnivan** [comment]
Sweet, thanks guys!

**Comment by pkiers** [comment]
Hello,

There are a cople of stories I wanted to share with you, please, read more here <http://discount.pizza-of-the-month.com/e2arb>

All best, p.kiers@home.nl
