### ISSUE TITLE
Versioning Changes? 

### ISSUE THREAD

**Issue by MeirionHughes** [GitTools/GitVersion#657]
Bit of an odd one; just switched to v3 and it doesn't seem to be reading from tags anymore: This intended?

![](http://i.imgur.com/5aEjpKu.png)

![](http://i.imgur.com/XhVU7g7.png)

**Comment by gep13** [comment]
What is the output of `git tag`

**Comment by MeirionHughes** [comment]
release-0.5
release-0.5.1
release-0.5.2

**Comment by gep13** [comment]
Those are the only tags that you have in your repo? :confused:

**Comment by MeirionHughes** [comment]
Yeah, I'd been deleting the redundant tags.

**Comment by gep13** [comment]
We would need to get the full debug output from running GitVersion in order to figure out where it is getting the base version from.

Have you also started changing the format of the tag?  i.e. I typically tag with just 0.5.1, rather than prefixing with release.  Also, what version of GitVersion did you upgrade from?

**Comment by MeirionHughes** [comment]
yes, that did it; tag with 0.6 works. Well, the 2.* gitversion config had release-*. 
Source tree automatically prefixes with release- as well. 

I guess I can edit the gitversion config. Although I was happy to not need one. :dancer:

**Comment by gep13** [comment]
>Source tree automatically prefixes with release- as well.

Really?  I also use SourceTree, and I haven't seen it do that.  I just get a free-form TextBox to input what I want.

**Comment by gep13** [comment]
Also, when you say:

>I'd been deleting the redundant tags.

What is the definition of redundant tag?

**Comment by MeirionHughes** [comment]
I think its because I set the prefix when I first enabled GitFlow on the repo. I probably shouldn't have deleted the old tags. It seemed tidier without them.

**Comment by gep13** [comment]
Ah, I see.  Yeah, I don't have anything in the versiontag in my config file.  Ok, so that makes sense again.

With regard to the breaking change, yeah, I think that was expected.  It was a major bump in version of GitVersion and a lot of stuff changed, including the detection logic to make it more consistent and maintainable.

**Comment by JakeGinnivan** [comment]
`tag-prefix` setting in GitVersionConfig.yaml can fix this. Default is `[vV]` but you can change to `([vV]|release-)` and that should fix up your issue.
