### ISSUE TITLE
Set VSO Build Number in Task

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#663]
See https://github.com/Microsoft/vso-agent-tasks/commit/815986b0f28ae56a522943127c3a18c016e0666b

The command is now available. Need to remove the note added in #577 and update docs as well.

**Comment by JakeGinnivan** [comment]
// @pascalberger

**Comment by robdmoore** [comment]
Nice!!! Exciting.

**Comment by pascalberger** [comment]
Nice, will update the docs accordingly

**Comment by JakeGinnivan** [comment]
We should update the actual task at the same time so it uses this feature automatically

**Comment by pascalberger** [comment]
Sure, can update the task too. Try to find out in which agent version this was/will be released.

IMHO the feature in the task should be optional, something like a combobox to choose to update build version number or not and choose the format (any of the GitVersion variables). Would this be OK for you?

**Comment by JakeGinnivan** [comment]
TeamCity updates this automatically, so you will need to introduce a switch or something which affects all build servers to opt out of the functionality

**Comment by pascalberger** [comment]
I've added a PR: #665 

I wasn't able yet to get this running on any VSO tenant, receiving the following message:

`##[warning]Unable to process logging event:##vso[build.updatebuildnumber]1.4.0-unstable.135`

I asked for this over at Microsoft/vso-agent-tasks#380.

**Comment by pascalberger** [comment]
With the latest VSO update this works now fine in my VSO accounts. Increased minAgentVersion for the task to 1.88 as by comment in https://github.com/Microsoft/vso-agent-tasks/issues/380#issuecomment-146878805.

@JakeGinnivan This should be ready to merge. Can you please review

**Comment by onovotny** [comment]
This doesn't go far enough, IMHO -- there should be an option to take the VSO build number and include that in the string somewhere.

What I'm proposing, and I can submit a PR for this, is to add a $(GITVERSION) marker into the existing VSO build number format string. VSO will ignore it because it doesn't understand it, but it will expand the rest.

If that string is present in the VSO build number (and it's readable via an env variable), then the VSO task will insert the build version in that location. Otherwise it'll do what it's currently doing.

That will enable richer build numbers that include things like branch names, etc.

**Comment by pascalberger** [comment]
Yeah, I also see this as a first step which has potential for further customization possibilities. At the moment it's implemented as it is implemented for other build servers (eg. TeamCity).

Best in my opinion would be if any of the GitVersion variables can be used in the VSO build number format string. VSO should expand their variables and GitVersion later it's variables. But this might require some changes to the IBuildServer interface since it currently fix passes FullSemVer and expects the build server implementation to return the message to set the build number. In the new scenario the build server implementation might decide on the version format to use.

**Comment by onovotny** [comment]
I agree that any of the GitVersion vars should be usable there.

I don't think a change is required to the IBuildserver interface though as the task can read the version string from the environment variable -- it doesn't need to be passed in.

Basically the set build number method would just loop through the env version string, looking for/replacing GitVersion vars with the real values and then output that final string.

Should I tee up a PR for that, at least for VSO?

**Comment by pascalberger** [comment]
Sure, that would work. 

I would prefer to update the `IBuildserver` interface to no longer pass the version to use to the `GenerateSetVersionMessage` function, since this will be ignored in this case for VSO. 

Would be cool if you could write a PR for this.

**Comment by onovotny** [comment]
If that version were removed, what should it use for the other build servers?

**Comment by pascalberger** [comment]
In my idea this needs to be decided by each build server implementation in the future, as it is no longer the same behavior for all build servers. 

Or we keep it and look at it as some sort of default version number to use, but IMHO it will be confusing for the caller if he calls `IBuildServer.GenerateSetVersionMessage('1.0')` and gets a version message for a completely different format back as it will be the case with the VSO implementation.

**Comment by JakeGinnivan** [comment]
https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/BuildServers/AppVeyor.cs actually already does what you are asking I think?

Sent from my Windows Phone
________________________________

**Comment by JakeGinnivan** [comment]
Same approach could be taken with VSO. I have only skimmed this thread so let me know if I missed something

Sent from my Windows Phone
________________________________

**Comment by pascalberger** [comment]
For AppVeyor only the build number is added to the fix version number. 

The idea for VSO is that it should take the build format set on the build definition, which can contain any GitVersion variable and expand them with the current value. Which is different to the AppVeyor implementation as it might be different version numbers.

**Comment by pascalberger** [comment]
In which case I think it would be appropriate to pass the whole `VersionVariables` (instead of `VersionVariables.FullSemVer`) to the build server implementation and let the implementation decide what to do with it

**Comment by onovotny** [comment]
When I start a PR for this, should I go off of master or the 4.0 branch? I think @pascalberger's suggestion of passing `VersionVariables` into the interface and letting the current impl just ues `FullSemVer` keeps existing behavior. But it is a breaking change to the interface.

**Comment by JakeGinnivan** [comment]
We are not maintaining semver in apis atm. More behaviour and usage.

Sent from my Windows Phone
________________________________
