### ISSUE TITLE
error CS0579: Duplicate 'AssemblyVersion' attribute when using shared assembly info

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#871]
Pretty sure this is related to #760 

In shouldly we have a Shared project with shared assembly info and then define the [AssemblyVersion] attribute in each of the projects themselves. 

The breaking change is that when you do not specify a filename GitVersion still injects the attributes into all files. I think it should only inject if a filename is specified?

Thoughts @Philo @gep13

**Comment by Philo** [comment]
I'll look at this when I return from holiday at the start of june

**Comment by asbjornu** [comment]
@JakeGinnivan I think the clever thing to do would be to:

1. Figure out which `AssemblyInfo` files are included in a project.
2. Search for existing `Assembly*Version` attributes in found files.
3. If attributes are found, patch the file with new attribute values.
4. If not found, add the (missing) attribute(s) to the file with the shortest path?

Not sure what we should do in step 4 to figure out which file to add the attribute to, though.

**Comment by Halling69** [comment]
I've had the the Duplicate AssemblyVersion attribute problem and has isolated it to whitespacing in old versions of VisualStudio:

Snippet of the AssemblyInfo.cs:
// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion( "1.0.0.0" )]
[assembly: AssemblyFileVersion( "1.0.0.0" )]


[end snippet]

because of the C# syntactically correct whitespaces, the ReGex dosn't match and inserts a new  AssemblyVersion attibute, that is then detrected by compiler as duplicate.

FIX: Change regex patterns in AssemblyInfoFileUpdate.cs :+1: From 
Regex(@"AssemblyVersion\(""[^""]*""\)")
to
Regex(@"AssemblyVersion\s*\(\s*""[^""]*""\s*\)") 

I'll see if I can put a pull request together
