### ISSUE TITLE
Question about support branches

### ISSUE THREAD

**Issue by cmacdonnacha** [GitTools/GitVersion#900]
Hi,

I'm not too sure if this is the correct place to ask this but I read your awesome [docs](https://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow-examples/#support-branches) on the use of **support branches** in gitflow and I was wondering if it would be a good idea to merge a hotfix (1.3.1) or feature (release/1.4.0) back into develop or master so that the next release (2.0) also has the changes?

Thanks,
Cathal.

**Comment by gep13** [comment]
@cmacdonnacha I am not sure if I follow your question...

>and I was wondering if it would be a good idea to merge a hotfix (1.3.1) or feature (release/1.4.0) back into develop or master

This sounds specifically what GitFlow suggests that you should do.  Can you clarify?

**Comment by JakeGinnivan** [comment]
Not sure if we actually link to the original GitFlow blog post. @cmacdonnacha have you read http://nvie.com/posts/a-successful-git-branching-model/ ?

But I do see what you mean, the diagrams are not really complete because it's subjective. Being a major version behind merging is often not feasible due to refactoring and such.
So *if* you can forward merge the updated support branch into develop then great. otherwise often it will require the hotfix to be made manually twice (assuming that bug even exists in the current develop). This is often easier than trying to merge to a codebase which has moved on significantly (which if you are using support branches, this is likely).

**Comment by JakeGinnivan** [comment]
And you only need to worry about getting that change into develop, it will end up on master through the normal gitflow workflows.

**Comment by cmacdonnacha** [comment]
@gep13 In the diagrams [here](https://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow-examples/#support-branches) you can see that *hotfix/1.3.1* was fixed and merged back into *support/1.x* but it looks like it's never merged back to master or develop. I was wondering if it should be?

@JakeGinnivan Yea I think the best option would be to merge a hotfix which is on a support branch to the develop branch as well so that it too has the hotfix. I know that there are some cases where you won't want or have to do this.

**Comment by gep13** [comment]
@cmacdonnacha gotcha, I see where you are coming from.  In this area, I think I have to agree with @JakeGinnivan. Merging this branch into develop would be on a case by case basis, depending on what actually changed.

**Comment by cmacdonnacha** [comment]
Perfect! Thanks guys!
