### ISSUE TITLE
gitversion manifest.json?

### ISSUE THREAD

**Issue by tofutim** [GitTools/GitVersion#935]
Hi, are there any special tips on using gitversion to update a manifest.json?

**Comment by gep13** [comment]
@tofutim there is nothing out of the box in GitVersion that will do this for you, but you should be able to consume the generated variables from GitVersion and update the json file yourself.

**Comment by tofutim** [comment]
darts, I was hoping for something as sweet as GitVersionTask :)

**Comment by gep13** [comment]
>@tofutim said....
darts, I was hoping for something as sweet as GitVersionTask :)

Unfortunately not.  There is a concept that GitVersion should do one thing and one thing only, i.e. assert the version numbers.  From there, it is the responsibility of an upstream process to do the other work.  In the case of the assemblyinfo files, that is "in the box" because that is the "norm". Updating other files is really outwith the scope of GitVersion.

**Comment by asbjornu** [comment]
I consider this question answered. If this is a feature request, please submit a PR. 😃 Closing.
