### ISSUE TITLE
Docs for building PRs with VSTS

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#993]
VSTS seems to specify a refspec when fetching, something like this:

```
git -c http.extraheader="AUTHORIZATION: bearer ********" fetch --tags --prune --progress origin +refs/pull/31/merge:refs/remotes/pull/31/merge
```

This means it doesn't fetch master or develop.

The workaround is:
1. Add a `git fetch` task in  
   ![image](https://cloud.githubusercontent.com/assets/453152/17546206/968effee-5f13-11e6-9361-337218d0f813.png)
   The argument should be `-c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" fetch --prune --progress origin`
2. Turn on allow scripts to access OAuth token.  
   ![image](https://cloud.githubusercontent.com/assets/453152/17546225/b7680d46-5f13-11e6-9e4b-e9b047771404.png)

We need to add this info to the docs.

**Comment by pascalberger** [comment]
I'm not sure this is always the best way to to go. There is also another issue that tags were not fetched in certain scenarios, for which there is already another workaround documented [here](http://gitversion.readthedocs.io/en/latest/build-server-support/build-server/tfs-build-vnext/), by setting the `build clean` variable. Also calling git directly depends which version of the agent is in use, the old agent used LibGit, with the new one it should be possible to call git directly.

IMHO it would be a better approach to document what is required for GitVersion to work properly (eg. have all tags fetched, have certain branches fetched, etc), and list the possible ways to achieve this with their pros/cons, so that the user can decide what best fits its setup.

**Comment by JakeGinnivan** [comment]
I don't know how to make pull requests fetch everything without this change? I am using on prem agents

**Comment by pascalberger** [comment]
@JakeGinnivan Ah yes, you're right. Seems to always checkout a ref.<

But instead of having the user to add an additional task to every build definition, wouldn't it be better if the GitVersion task would fetch the missing branches itself?

**Comment by JakeGinnivan** [comment]
This can probably be built into GitVersion itself to fetch automatically, and throw if the OAuth token is not available

**Comment by roryprimrose** [comment]
This would presumably be surfaced as an option on the GitVersion build step.

**Comment by JakeGinnivan** [comment]
It would be built into the core. Disabled with the /nofetch option.

**Comment by JakeGinnivan** [comment]
Your using on-premises build agents?

**Comment by roryprimrose** [comment]
Both actually. The one I'm currently troubleshooting is a hosted agent with the repository that just has some binaries and a nuspec.

Is there a recommended option for current versions that will sort out this PR issue and the possibility of tags not being fetched?

**Comment by JakeGinnivan** [comment]
Follow the instructions in the first post to work around it. I haven't had time to really take this further as this workaround worked for me

**Comment by roryprimrose** [comment]
First post being the extra build step outlined above? Seems like a good time to look at that new meta-task thingy :)

**Comment by JakeGinnivan** [comment]
heh, I don't want to make the workaround the primary fix. Id prefer we just build it in and make it transparent :)

**Comment by JakeGinnivan** [comment]
@nulltoken do you know if we can specify additional headers through libgit2sharp?

Need to do something like this `git -c http.extraheader="AUTHORIZATION: bearer <authtoken>" fetch --tags --prune --progress origin +refs/head/*:refs/remotes/origin/*`

**Comment by nulltoken** [comment]
@JakeGinnivan Not that I know of.

@ethomson @carlosmn Did you make something like this happen?

**Comment by ethomson** [comment]
@nulltoken No, we do not yet support this, though it seems like it would be a nice addition.  Patches welcome!  ;)

**Comment by nulltoken** [comment]
@ethomson Thanks for the feedback ❤️

**Comment by jessehouwing** [comment]
When built into the task itself, it will be able to access the oauth token without needing a special setting.

**Comment by pascalberger** [comment]
Since libgit2sharp doesn't seem to support passing an OAuth token, it may be the best solution at the moment to implement this in the VSTS task, and require the user to make the OAuth token available to the task and have Git installed on the agent (which should be no longer an issue using the new agent).

**Comment by jessehouwing** [comment]
The task itself is able to access the OAuth token directly using the following code (old powershell host, the code for powershell3 is very similar, but it looks like you're still on the old host):
```
$VSTSEndpoint = Get-ServiceEndpoint -Context $distributedTaskContext -Name "SystemVssConnection"
if ($VSTSEndpoint -eq $null)
{
    throw "Could not locate Service Endpoint SystemVssConnection."
}
$baererToken = $VSTSEndpoint.Authorization.Parameters.AccessToken
```

I'd personally stick a demand for git.exe on the task and have checkbox to perform `git fetch origin --tags` as part of the task execution.

You could skip the demand and perform a `find-command` to see if you can find `git.exe` from the session, or just package `mingw` as part of the task itself like Visual Studio 15 is doing since the latest preview `C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git` should have everything you need to package Git as part of your task..

**Comment by mikocot** [comment]
this issue is still a problem in 2022, while the pipeline definition is very different now than in the original post :/
