### ISSUE TITLE
Unable to remove -ci from master builds

### ISSUE THREAD

**Issue by MrHinsh** [GitTools/GitVersion#999]
Guys,

 I don't want to have the "-ci0015" appended to my MASTER builds when using ContinuousDeployment. How do I turn that off?

```
assembly-versioning-scheme: None
mode: ContinuousDeployment
next-version: 0.4.8
branches:
  master:
    mode: ContinuousDeployment
    tag: ''
ignore:
  sha: []
```

I have tried the above!

**Comment by gep13** [comment]
@MrHinsh what version of GitVersion are you using?  When you say you have tried the above, does that mean you have just now changed the yml file?  If so, have you cleared the `gitversion_cache` folder, in order to ensure that you are not seeing a cached version of the asserted version number being returned?

**Comment by MrHinsh** [comment]
I am building with 3.6.2 on the hosted service of VSTS, so its a fresh build server each time. 

![image](https://cloud.githubusercontent.com/assets/5205575/17580005/7dd7daa6-5fcd-11e6-8c84-11fc1d070ec1.png)

The value of "GITVERSION_NuGetVersionV2" includes "-ci.16" and on the MASTER branch I would want it to not include a pre-release tag... my CI has already passed the benchmarks and tests for release and I want to ship it. 

![image](https://cloud.githubusercontent.com/assets/5205575/17580031/ad8b6f74-5fcd-11e6-952e-4d694de96c39.png)

**How can I tell GitVersion that MASTER branch builds should never include a pre-release tag?**

**Comment by gep13** [comment]
@JakeGinnivan you around?

**Comment by pascalberger** [comment]
@MrHinsh How are you fetching the repository?. By default VSTS doesn't fetch all tags, which can lead to this behavior. 

See the [known limitations](http://gitversion.readthedocs.io/en/latest/build-server-support/build-server/tfs-build-vnext/) section in the documtation:

> You need to make sure that all tags are fetched for the Git repository, otherwise you may end with wrong versions (e.g. FullSemVer like 1.2.0+5 instead of 1.2.0 for tagged releases) Just checking the Clean Repository check box in the build definition settings might not be enough since this will run a git clean -fdx/reset --hard without fetching all tags later. You can force deletion of the whole folder and a re-clone containing all tags by settings the variable Build.Clean to all. This will take more time during build but makes sure that all tags are fetched. In the future it is planned to allow using git.exe instead of current libgit2sharp for syncing the repos which might allow other possibilities to solve this issue. For details see this [GitHub issue](https://github.com/Microsoft/vso-agent-tasks/issues/1218).

**Comment by qetza** [comment]
@MrHinsh add the following configuration `continuous-delivery-fallback-tag: ''`

> assembly-versioning-scheme: None
> mode: ContinuousDeployment
> continuous-delivery-fallback-tag: ''
> next-version: 0.4.8
> branches:
>   master:
>     mode: ContinuousDeployment
>     tag: ''
> ignore:
>   sha: []

Even though the variable is named continuous-delivery it is used on continuous deployment...

**Comment by JakeGinnivan** [comment]
@qetza doh, that is annoying. We should fix that.

@MrHinsh when continuous delivery was implemented we used this thinking: http://gitversion.readthedocs.io/en/latest/more-info/incrementing-per-commit. We didn't want to assume each commit was a bug fix (and each merged PR would skip a bunch of patch versions) so the only logical place to put it is in the pre-release tag. This ends up causing all sorts of issues, especially if you are publishing NuGet packages because pre-release is viral.

In v4 we are introducing a new mode called mainline, each merged branch or direct commit to master is treated as a release. So when you merge a PR you will only bump a single patch release, even if the branch contained 10 commits and is probably what you want. We still have some issues to work out with mainline development mode but hoping to get it out in the next week or two.

For now, you could build your own version number. i.e $(Major).$(Minor).$(Patch).$(PreReleaseNumber) to get a 4 part version number. Not the greatest solution.

Another way is to actually use Continuous Delivery mode, then I am assuming you are using VSTS release management. Your release number should contain the $(rr.rev) so you can deploy the same version again. Then when you promote to a particular environment add a task which goes back and tags your VCS which can bump the patch version number.

**Comment by JakeGinnivan** [comment]
Removing VSTS tag as this is actually not a VSTS issue.

**Comment by JakeGinnivan** [comment]
There are a few ways we could change the behavior. Unsure which is the best, each has it's downsides

## 1. Move to a 4 part version
 `+` No pre-release tag  
 `-` No longer follows SemVer  

Could also expose a FourPartNuGetVersion or something also to make it easy to pick this one up now.

## 2. Promote number of commits since base to patch
 `?` What happens to patch?
 `+` No pre-release tag
 `-` Skips multiple patch versions per release, also likely would not be able to just bump minor/major without patch being bumped as well because patch is counting commits now

Would love thoughts on which direction we should go.

**Comment by MrHinsh** [comment]
Having the option of [1] would be awesome, even if it is not SemVer... I would be interested in telemetery on its usage. 

I thought about [2] and rejected it for the reasons that you specified.

**Comment by qetza** [comment]
@JakeGinnivan i think number 1 could be done by exposing a new variable and could be extremely usefull even without nuget. For example when dealing with MSI installer, file version with 4 parts are used to know if a file need to be changed, currently i'm recreating this 4 part version in build scripts using CommitsSinceVersionSource.

@MrHinsh seems like a bug because, it should be 18 like GITVERSION_COMMITSSINCEVERSIONSOURCE. I'll look into this.

**Comment by JakeGinnivan** [comment]
We should actually try and do some opt in telemetry, would be super useful. Though exposing a new variable would not give us telemetry on their use and I want to avoid new options, it's already pretty confusing.

I am working on http://gitversion.readthedocs.io/en/latest/reference/mainline-development which at the moment seems like it will be a great compromise. Though there is still bugs in v4 so not deploying to VSTS because you cannot choose the version you are running. You would have to switch to command line to test or put GitVersion into your build scripts (Cakebuild.net has great support).

**Comment by MrHinsh** [comment]
OK, so my .yml file now looks like:
```
assembly-versioning-scheme: None
mode: ContinuousDeployment
continuous-delivery-fallback-tag: ''
next-version: 0.4.8
branches:
  master:
    mode: ContinuousDeployment
    tag: ''
ignore:
  sha: []
```
However now I can only increment major with +semver:major and nothing happens when I do +semver:minor or +semver:patch...

![image](https://cloud.githubusercontent.com/assets/5205575/17685321/6f6f2c3c-6395-11e6-9041-94d4009eb4f9.png)

I would have expected both minor and patch to increment as normal...

**Comment by JakeGinnivan** [comment]
`+semver:` messages are a hint rather than a command.

For instance if I have `+semver: minor` in a commit, then `+semver: major` then `+semver:minor` in a single PR then GitVersion will simply bump major. Both continuous delivery and continuous deployment will calculate this since the last tag. So without tagging commits with the built version this won't work for you :(

When v4 drops Mainline mode will sort your issue though. It treats each merged branch and direct commits against master as a release, then aggregate each increment.

You can give it a try by using the command line outside of VSTS, or try uploading the vsix from https://github.com/GitTools/GitVersion/releases/tag/v4.0.0-beta.5, but unsure you can upload beta releases (we don't push beta releases into VSTS as it will automatically upgrade everyone before we are entirely happy).

**Comment by MrHinsh** [comment]
Even with a single +semver:minor in a commit to master there is no bump in version at all when using the .yml above. guestimate of when you plan onshipping 4.0?

Do you have a

**Comment by ryudice** [comment]
Was this addressed at some point?

**Comment by martinfletcher** [comment]
Any update on this?

**Comment by JakeGinnivan** [comment]
Continuous deployment mode will always add this, the docs link to a blog post which explains the reason quite well.

We really need to release v4 stable soon, but if you grab the beta, mainline mode probably does exactly what you want.

**Comment by JakeGinnivan** [comment]
See https://gitversion.readthedocs.io/en/latest/reference/mainline-development/ for info on mainline mode

**Comment by kinguru** [comment]
Just merged 6.17.1 to the master, and got 6.17.0-ci.204 from master build. Is it ok?

**Comment by oswaldozapata** [comment]
I had same issue, but I got this fixed doing this:
[Configuration](https://gitversion.net/docs/reference/configuration)
```

continuous-delivery-fallback-tag
When using mode: ContinuousDeployment, the value specified in continuous-delivery-fallback-tag will be used as the pre-release tag for branches which do not have one specified. Default set to ci.

Just to clarify: For a build name without ...-ci-<buildnumber> or in other words without a PreReleaseTag (ergo "PreReleaseTag":"" in GitVersion's JSON output) at the end you would need to set continuous-delivery-fallback-tag to an empty string (''):

mode: ContinuousDeployment
continuous-delivery-fallback-tag: ''
...
Doing so can be helpful if you use your main branch as a release branch.
```

**Comment by EmilAlipiev** [comment]
This is possibly outdated version 5.12.0 doesnt have any property called continuous-delivery-fallback. What is the solution here? 

https://github.com/GitTools/GitVersion/blob/1ae5536d225795790f430aa38c618cb93d0fe855/src/GitVersion.Configuration/BranchConfiguration.cs#L7

**Comment by EmilAlipiev** [comment]
What is document here is also not matching! I have tried both continuous-delivery-fallback-tag and continuous-delivery-fallback-label  and both are not found. 

https://github.com/GitTools/GitVersion/blob/1ae5536d225795790f430aa38c618cb93d0fe855/BREAKING_CHANGES.md?plain=1#L2

**Comment by asbjornu** [comment]
@EmilAlipiev, `BREAKING_CHANGES.md` is contradicting itself. On line 23-24, it says this:

https://github.com/GitTools/GitVersion/blob/1ae5536d225795790f430aa38c618cb93d0fe855/BREAKING_CHANGES.md?plain=1#L23-L24
